// idioma/en.js
// Diccionario English. Clave = texto original en español (LatAm), Valor = traducción.
// Coincidencia EXACTA (recortando espacios). Cubre: interfaz completa, novedades,
// filtros/footer, etiquetas de tarjetas de jugador y combinaciones de torneo/resultado.

var ZC_LANG_EN = {
    "% de Victoria": "Win %",
    "0": "0",
    "0-2": "0-2",
    "0.0": "0.0",
    "0/11": "0/11",
    "08/09/26": "08/09/26",
    "1": "1",
    "1-2": "1-2",
    "104.0": "104.0",
    "11 Rondas": "11 Rounds",
    "11/11": "11/11",
    "118.4": "118.4",
    "129.9": "129.9",
    "132.5": "132.5",
    "15": "15",
    "153.1": "153.1",
    "17', 26'": "17', 26'",
    "19": "19",
    "1er Lugar": "1st Place",
    "1er lugar · 120 pts": "1st place · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 0 · 120 pts": "1st place · Sets 4 - 0 · W-L 9 - 0 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 2 · 120 pts": "1st place · Sets 4 - 0 · W-L 9 - 2 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 4 · 120 pts": "1st place · Sets 4 - 0 · W-L 9 - 4 · 120 pts",
    "1st": "1st",
    "1st Champion": "1st Champion",
    "2": "2",
    "2-1": "2-1",
    "20": "20",
    "20'": "20'",
    "25%": "25%",
    "26": "26",
    "27": "27",
    "2do Lugar": "2nd Place",
    "2do lugar · 80 pts": "2nd place · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 6 - 4 · 80 pts": "2nd place · Sets 3 - 1 · W-L 6 - 4 · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 8 - 4 · 80 pts": "2nd place · Sets 3 - 1 · W-L 8 - 4 · 80 pts",
    "2nd": "2nd",
    "2nd Runner-Up": "2nd Runner-Up",
    "3": "3",
    "34": "34",
    "34'": "34'",
    "3er Lugar": "3rd Place",
    "3er lugar · 105 pts": "3rd place · 105 pts",
    "3er lugar · 50 pts": "3rd place · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 6 - 2 · 50 pts": "3rd place · Sets 3 - 1 · W-L 6 - 2 · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 7 - 2 · 50 pts": "3rd place · Sets 3 - 1 · W-L 7 - 2 · 50 pts",
    "3er lugar · Sets 3 - 2 · PG-PP 7 - 6 · 50 pts": "3rd place · Sets 3 - 2 · W-L 7 - 6 · 50 pts",
    "3er y 4to Lugar": "3rd and 4th Place",
    "3er-4to Lugar": "3rd-4th Place",
    "3rd-4th Place": "3rd-4th Place",
    "3rd-4th place": "3rd-4th place",
    "4to Lugar": "4th Place",
    "4to lugar · 100 pts": "4th place · 100 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 4 - 4 · 45 pts": "4th place · Sets 2 - 2 · W-L 4 - 4 · 45 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 5 - 4 · 45 pts": "4th place · Sets 2 - 2 · W-L 5 - 4 · 45 pts",
    "5.8": "5.8",
    "6.0": "6.0",
    "60": "60",
    "7.1": "7.1",
    "7.6": "7.6",
    "75%": "75%",
    "8'": "8'",
    "8.6": "8.6",
    "80.8": "80.8",
    "81": "81",
    "9": "9",
    "9.4": "9.4",
    "94.8": "94.8",
    "98.0": "98.0",
    "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aporte al equipo.": "On an individual level, the player Taikisha was recognized as the most outstanding figure of the event for their brilliant performance throughout the matches, receiving a special bonus for their contribution to the team.",
    "Abrir menú": "Open menu",
    "Actividad": "Activity",
    "Activo": "Active",
    "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competencia.": "In addition, we will have a moderation team dedicated to reviewing each match closely, ensuring that the environment remains clean, respectful, and orderly during the competition days.",
    "Agradecemos la participación de todos los competidores y les invitamos a mantenerse atentos a las próximas ediciones.": "We thank the participation of all competitors and invite you to stay tuned for upcoming editions.",
    "Al conseguir los créditos necesarios, se abrirá una pantalla especial donde se mostrarán los personajes disponibles. Al tocar la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.": "Upon obtaining the necessary credits, a special screen will open showing the available characters. By tapping the screen, the options will be eliminated one by one until revealing the obtained character.",
    "Alineaciones": "Lineups",
    "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.": "Before the start of the clashes in the grand final, both teams applied their strategy in the ban phase. The characters Belle, Spike, Bibi, and Nori were excluded from the match, forcing the squads to rethink their tactical compositions for the decisive series.",
    "Apoyamos y síguenos en nuestras redes sociales": "Support and follow us on our social media",
    "ASIA": "ASIA",
    "Argentina": "Argentina",
    "As de Combate": "Combat Ace",
    "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatorio.": "Likewise, on August twenty-ninth, one thousand five hundred credits will be delivered as compensation for the adjustments in the system. Players will be able to decide whether to use these credits before the update to get the character they are currently unlocking or save them for the new random system.",
    "Asist.:": "Assists:",
    "Asistencias": "Assists",
    "Así se jugó la final: Leviatán se impuso 3-1 en los mapas": "How the final was played: Leviatán prevailed 3-1 in maps",
    "Ataques": "Attacks",
    "Aug 8, 26": "Aug 8, 26",
    "Aún no hay estadísticas de defensa registradas para este partido.": "There are no defense statistics recorded for this match yet.",
    "Balance de mapas o modos ganados y perdidos.": "Balance of maps or modes won and lost.",
    "Balance de sets ganados y perdidos en la competencia.": "Balance of sets won and lost in the competition.",
    "Baneos globales": "Global bans",
    "Belle rock": "Belle's Rock",
    "Bolivia": "Bolivia",
    "Brasil": "Brazil",
    "Capacidad para controlar el mapa y mantener buena posición durante la partida.": "Ability to control the map and maintain good positioning during the match.",
    "Capacidad para sobrevivir y reducir el daño recibido en combate.": "Ability to survive and reduce damage taken in combat.",
    "Chile": "Chile",
    "Colombia": "Colombia",
    "Contribución en la captura o cumplimiento de los objetivos del modo.": "Contribution to capturing or completing the mode's objectives.",
    "Control de Zona y Posicionamiento": "Zone Control & Positioning",
    "EMEA (Europa, Medio Oriente y África)": "EMEA (Europe, Middle East & Africa)",
    "Ecuador": "Ecuador",
    "Eficiencia en Combate (K/D/A)": "Combat Efficiency (K/D/A)",
    "El Salvador": "El Salvador",
    "España": "Spain",
    "Ghana": "Ghana",
    "Gran Maestro de Combate": "Combat Grandmaster",
    "Guatemala": "Guatemala",
    "Habilidades": "Skills",
    "Honduras": "Honduras",
    "Impacto y Uso del Súper": "Super Impact & Usage",
    "K/D/A": "K/D/A",
    "L. Puppies Represent": "L. Puppies Represent",
    "LEVIATÁN ESPORTS se coronó campeón de la Gran Final ZC26 el 09/08/26 tras vencer 3-1 a Cachorritas repres (LPR). Título obtenido con la alineación de Julio (capitán), iXLCross y JOAR.": "LEVIATÁN ESPORTS was crowned champion of the ZC26 Grand Final on 09/08/26 after defeating Cachorritas repres (LPR) 3-1. The title was won with the lineup of Julio (captain), iXLCross, and JOAR.",
    "Leviatán Esports": "Leviatán Esports",
    "Maestro de Combate": "Combat Master",
    "Mapas": "Maps",
    "Mayor descenso": "Biggest Drop",
    "Mejor clasificación": "Best Ranking",
    "Más puntos conseguidos": "Most Points Gained",
    "Más puntos perdidos": "Most Points Lost",
    "México": "Mexico",
    "Norteamérica": "North America",
    "Objetivos": "Objectives",
    "Perú": "Peru",
    "Pool": "Pool",
    "Porcentaje de Victorias": "Win Percentage",
    "Porcentaje de partidas o sets ganados sobre el total jugado.": "Percentage of matches or sets won out of the total played.",
    "Potencial": "Potential",
    "Promedio de Puntos por Torneo": "Average Points per Tournament",
    "Pts/Torneo": "Pts/Tournament",
    "Puntos obtenidos en promedio por cada torneo disputado.": "Points earned on average per tournament played.",
    "Qué tan efectivo es usando su habilidad Súper en el momento correcto.": "How effectively they use their Super ability at the right moment.",
    "Qué tan variado y flexible es su repertorio de personajes al draftear.": "How varied and flexible their character pool is when drafting.",
    "Rango Mítico": "Mythic Rank",
    "Relación entre eliminaciones, muertes y asistencias en combate.": "Ratio of kills, deaths, and assists in combat.",
    "Reputación Int.": "Int'l Reputation",
    "Récord de Mapas/Modos (PG-PP)": "Maps/Modes Record (W-L)",
    "Récord de Sets (G-P)": "Sets Record (W-L)",
    "Sudamérica": "South America",
    "Superviv.": "Surviv.",
    "Supervivencia y Mitigación de Daño": "Survival & Damage Mitigation",
    "Súper": "Super",
    "Toma de Objetivos del Modo de Juego": "Game Mode Objective Control",
    "Venezuela": "Venezuela",
    "Versatilidad de Pool (Drafteo)": "Pool Versatility (Drafting)",
    "Victorias %": "Win %",
    "Zona": "Zone",
    "belle y spike": "Belle and Spike",
    "Bibi y Nori": "Bibi and Nori",
    "Brawl Ball": "Brawl Ball",
    "Brawl Stars Oficial": "Official Brawl Stars",
    "Brawl Stars · Agosto 8 de 2026": "Brawl Stars · August 8, 2026",
    "BRAWLER BLAST": "BRAWLER BLAST",
    "Brawlers principales": "Main Brawlers",
    "BSC, AUG 8": "BSC, AUG 8",
    "Buscar por nombre, ID o país...": "Search by name, ID or country...",
    "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, como puntos de fuerza, gadgets, habilidades estelares, engranajes o hipercargas. Siempre se asegurará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.": "Each discard will grant gem shards that will directly convert into upgrades for the character, such as power points, gadgets, star powers, gears, or hypercharges. At least one power level will always be ensured, with the possibility of getting a fully maxed-out character.",
    "Calificaciones de los jugadores (0/11) basadas en los datos de los partidos": "Player ratings (0/11) based on match data",
    "Calificación del jugador": "Player Rating",
    "Campeones a lo largo de los torneos ZC26": "Champions across ZC26 tournaments",
    "Campeón": "Champion",
    "Campeón · 500 pts · +25 Estelar (Set 1)": "Champion · 500 pts · +25 Estelar (Set 1)",
    "Campeón · 500 pts · +25 Estelar (Set 3)": "Champion · 500 pts · +25 Estelar (Set 3)",
    "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP": "Champion · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP",
    "Campeón · Suplente (no disputó rondas)": "Champion · Substitute (did not play rounds)",
    "Champion": "Champion",
    "Clasificación actual": "Current Ranking",
    "Clasificatoria": "Ranked",
    "Coach": "Coach",
    "COMENTARIOS": "COMMENTS",
    "Con estos resultados, la tabla general de posiciones quedó encabezada por Leviatán Esports en el primer lugar, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.": "With these results, the overall standings table was headed by Leviatán Esports in first place, escorted by the runner-up in the second slot, and closing the podium with the third place of the tournament.",
    "Contacto": "Contact",
    "Contacto comercial y soporte:": "Commercial contact and support:",
    "Contribucion": "Contribution",
    "Contribución total": "Total Contribution",
    "Copyrights © ZC ESPORTS 2026": "Copyrights © ZC ESPORTS 2026",
    "CREDITOS": "CREDITS",
    "Cronología": "Timeline",
    "Créditos aprox.": "Approx. Credits",
    "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.": "When a new character is added to the game, it will be added to the list of its respective rarity and can appear in Brawler Blast, although its immediate unlocking cannot be prioritized.",
    "Datos de Brawl Stars": "Brawl Stars Data",
    "Datos destacados": "Highlights",
    "Defensas": "Defenses",
    "Descenso": "Drop",
    "Después de ese evento, nos tomamos un tiempo fuera de las canchas para planificar todo con calma, pero la espera terminó y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta oportunidad, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.": "After that event, we took some time away from the courts to plan everything calmly, but the wait is over and we are officially back with a new installment of ZC26. This time, we will once again measure everyone's level in the three-versus-three mode within Brawl Stars.",
    "Discord": "Discord",
    "doble swoosh": "Double Swoosh",
    "DPS:": "DPS:",
    "Edición 4": "Edition 4",
    "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se jugó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.": "The development of the final encounter showed a firm performance by Leviatán Esports, overcoming their rival by a score of three sets to one. The first set was played on the Mad Tires map, where Leviatán took the initial advantage with a clean two-to-zero victory.",
    "El encuentro terminó.": "The match has ended.",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast": "The Starr Road system will be replaced by a new mechanic called Brawler Blast",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de manera aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.": "The Starr Road system will be replaced by a new mechanic called Brawler Blast. With this change, upon gathering the required amount of credits, a character will be randomly unlocked within a certain rarity, additionally granting extra progression for said character.",
    "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su final, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competencia estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.": "The official Brawl Stars three-versus-three tournament has reached its end, crowning Leviatán Esports as the grand champion of this inaugural edition. The day of competition was marked by an outstanding technical level and high-intensity series in each of the played rounds.",
    "Eliminaciones (Kills)": "Eliminations (Kills)",
    "EMEA": "EMEA",
    "En el segundo mapa, Roca de Belle, el conjunto rival logró responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un categórico dos a cero.": "In the second map, Belle's Rock, the rival team managed to respond and tie the series by claiming the point with a two-to-one result. However, Leviatán regained control of the actions in the third map, Lush Bushes, prevailing two to one in a heavily contested duel, and finally closed the championship on the Double Swoosh map with a categorical two to zero.",
    "Equipo": "Team",
    "Equipo de Apoyo": "Support Team",
    "Estado": "Status",
    "Escalafón": "Ladder",
    "Estadísticas": "Statistics",
    "Estadísticas clave": "Key statistics",
    "Estadísticas del partido": "Match statistics",
    "Estadísticas generales del partido": "Overall match statistics",
    "Estadísticas y rendimiento competitivo": "Competitive Stats & Performance",
    "Estimada comunidad, nos alegra mucho ponernos en contacto con ustedes para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordarán, en la última edición el equipo de Levantan Esports se quedó con el primer lugar tras una excelente participación.": "Dear community, we are very glad to contact you to share several important updates about the development of our tournaments. As you may recall, in the last edition the Levantan Esports team took first place after an excellent participation.",
    "Eventos:": "Events:",
    "Faltas": "Fouls",
    "Filtro": "Filter",
    "Filtros": "Filters",
    "Fin": "End",
    "Finalized": "Finalized",
    "Finished": "Finished",
    "Ganancias aprox.": "Approx. Earnings",
    "Gem Grab": "Gem Grab",
    "Gmail": "Gmail",
    "GRAN FINAL": "GRAND FINAL",
    "Gran Final": "Grand Final",
    "Gran Final 🏆": "Grand Final 🏆",
    "Heist": "Heist",
    "Highlights": "Highlights",
    "Historias destacadas": "Top stories",
    "Home": "Home",
    "HOME": "HOME",
    "IDs alternos": "Alternate IDs",
    "Imagen no disponible": "Image not available",
    "Inactivo": "Inactive",
    "Información": "Information",
    "Información del jugador": "Player Information",
    "Información general": "General information",
    "iXCross": "iXCross",
    "iXLCross": "iXLCross",
    "JOAR": "JOAR",
    "Juanjo": "Juanjo",
    "Juanjoxd": "Juanjoxd",
    "Jugador": "Player",
    "Jugador Sorpresa": "Surprise Player",
    "Julio": "Julio",
    "Juliocr36D": "Juliocr36D",
    "Kills:": "Kills:",
    "Knockout": "Knockout",
    "L. Puppies Represent · Titulares": "L. Puppies Represent · Starters",
    "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competencia intensa donde solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.": "The tournament structure is designed to keep the excitement from start to finish, as it will be an intense competition where only one team will manage to take home the champion trophy. We know the demands are high, so we expect to see very disputed matches between the best groups that show up.",
    "La ZC26 vuelve este septiembre": "ZC26 returns this September",
    "leafy bushes": "Leafy Bushes",
    "LEV": "LEV",
    "LEV WINNER": "LEV WINNER",
    "LEVIATÁN ESPORT · Titulares": "LEVIATÁN ESPORT · Starters",
    "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 Agosto": "LEVIATÁN ESPORTS crowned CHAMPION of ZC26 August",
    "Lo más destacado del ranking": "Ranking highlights",
    "Logros": "Achievements",
    "Los invitamos a ponerse de acuerdo con sus compañeros, armar sus alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que manténganse atentos a los anuncios.": "We invite you to agree with your teammates, put together your lineups in time, and start practicing. In the next few days we will continue posting more details about schedules and the registration method, so stay tuned for announcements.",
    "LPR": "LPR",
    "Lugar:": "Location:",
    "MATCHES, AUG 8": "MATCHES, AUG 8",
    "Mayor a menor": "Highest to lowest",
    "Mayor bajada": "Biggest Drop",
    "Mayor subida": "Biggest Rise",
    "Mejor Clasificación": "Highest Ranking",
    "Mejor contribución": "Best Contribution",
    "Mejor jugada": "Best play",
    "MEJOR JUGADA": "BEST PLAY",
    "Menor a mayor": "Lowest to highest",
    "Modalidad: 3 vs 3 · Bo5 · Tier S": "Mode: 3 vs 3 · Bo5 · Tier S",
    "Momentos de la BSC de la ZC26™": "ZC26™ BSC Moments",
    "Mostrar Clasificación completa": "Show full ranking",
    "Mostrar menos": "Show less",
    "Mostrar más": "Show more",
    "mostrar más": "show more",
    "Movimiento": "Movement",
    "MVP:": "MVP:",
    "Más info.": "More info",
    "Más información sobre": "More information about",
    "Más partidos": "More matches",
    "MÁS ZC26": "MORE ZC26",
    "N/A": "N/A",
    "NA": "NA",
    "Nacaru": "Nacaru",
    "Nacimiento": "Birth",
    "Nacionalidad": "Nationality",
    "Nada": "None",
    "NEW": "NEW",
    "Ninja": "Ninja",
    "No hace falta ser un experto en competencias para sumarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.": "You don't need to be a competition expert to join; the guides and instructions are written simply so everyone knows exactly how to register, how to report their results, and how to advance in each phase.",
    "No hay logros registrados": "No achievements recorded",
    "No se encontró ningún jugador con estos filtros.": "No player found with these filters.",
    "No se encontró ningún jugador.": "No player found.",
    "No se pudo cargar el archivo de idioma:": "Could not load language file:",
    "Nueva clasificación más alta": "New highest ranking",
    "Nuevo": "New",
    "Ocultar Clasificación completa": "Hide Full Ranking",
    "Orden": "Order",
    "Organización del Evento: ZC26 BSC (Brawl Stars Championship)": "Event Organization: ZC26 BSC (Brawl Stars Championship)",
    "Otro punto en el que pusimos mucho esfuerzo fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.": "Another point where we put a lot of effort was in the clarity of the rulebook. We want anyone who feels like playing to be able to understand the format without complications, even if it is their first time participating in such a tournament.",
    "Para esta edición decidimos renovar varias cosas. Incorporamos nuevas reglas y mecánicas de juego que buscan equilibrar la cancha para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.": "For this edition we decided to renovate several things. We incorporated new rules and gameplay mechanics that seek to level the playing field for all participants. The main idea is that each team competes under equal conditions, with no unfair advantages for anyone.",
    "Partidas (PG-PP):": "Matches (W-L):",
    "Partidas recientes": "Recent Matches",
    "Partners": "Partners",
    "PARTNERS": "PARTNERS",
    "PayPal": "PayPal",
    "País": "Country",
    "Peor clasificación": "Lowest Ranking",
    "PG-PP": "W-L",
    "Player Tag / Player ID": "Player Tag / Player ID",
    "Por confirmar": "To be confirmed",
    "Porcentaje de victorias": "Win Rate",
    "Posiciones": "Standings",
    "Posición en el ranking": "Ranking Position",
    "Posición promedio": "Average Position",
    "PREMIOS": "AWARDS",
    "Promedio de puntos por torneo": "Average Points per Tournament",
    "Promedio DPS de Equipo": "Average Team DPS",
    "pts": "pts",
    "puedes obtener beneficios dentro de la comunidad.": "you can get benefits within the community.",
    "Punto de campeonato": "Championship point",
    "PUNTO DE CAMPEONATO": "CHAMPIONSHIP POINT",
    "Puntos totales:": "Total Points:",
    "Ranking": "Ranking",
    "RANKING": "RANKING",
    "Reconocimientos especiales": "Special Recognitions",
    "Redes oficiales:": "Official networks:",
    "Redes sociales": "Social media",
    "Región": "Region",
    "Regresa la ZC26 Brawl Stars este mes de septiembre": "ZC26 Brawl Stars returns this September",
    "Regresar": "Return",
    "Restablecer filtros": "Reset filters",
    "RESUMEN AGOSTO": "AUGUST SUMMARY",
    "Rol": "Role",
    "Ronda 1": "Round 1",
    "Ronda 2": "Round 2",
    "Rondas Ganadas (Sets)": "Rounds Won (Sets)",
    "Rondas:": "Rounds:",
    "Récord de mapas/modos (PG-PP)": "Map/Mode Record (W-L)",
    "Récord de sets (G-P)": "Set Record (W-L)",
    "SA": "SA",
    "SALON DE LA FAMA": "HALL OF FAME",
    "Salón de la fama": "Hall of Fame",
    "Salón de la Fama": "Hall of Fame",
    "Sanciones": "Penalties",
    "Se actualiza con cada contribucion a ZC26": "Updates with every contribution to ZC26",
    "Se actualiza con cada torneo de ZC26": "Updates with every ZC26 tournament",
    "Según los datos de los partidos": "Based on match data",
    "Seleccion completa": "Full selection",
    "Semifinal": "Semifinal",
    "Servidores Globales, Brawl Stars": "Global Servers, Brawl Stars",
    "Set Marcado:": "Set Scored:",
    "Sets": "Sets",
    "Sets (G-P):": "Sets (W-L):",
    "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como corrección de nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor contáctanos a través de los medios oficiales indicados arriba.": "If you wish to request any modification regarding your identity on the page — such as correction of name, region, date of birth, nickname, social media, or other data associated with your profile — please contact us through the official channels indicated above.",
    "Silenciar sonidos": "Mute sounds",
    "Sin partidas registradas": "No matches recorded",
    "Subcampeón": "Runner-up",
    "Subcampeón · 250 pts": "Runner-up · 250 pts",
    "Subcampeón · 250 pts · +25 Estelar (Set 2)": "Runner-up · 250 pts · +25 Estelar (Set 2)",
    "Subida": "Rise",
    "Suplente · LEV": "Substitute · LEV",
    "Suplentes": "Substitutes",
    "Sí": "Yes",
    "TA:": "YC:",
    "Taikisha, elegido MVP de la Gran Final": "Taikisha, chosen MVP of the Grand Final",
    "TAIKISHA, MVP": "TAIKISHA, MVP",
    "Taikisha, MVP 🏆": "Taikisha, MVP 🏆",
    "Tarjetas Amarillas": "Yellow Cards",
    "Tarjetas Rojas": "Red Cards",
    "TikTok": "TikTok",
    "tire maniacs": "Tire Maniacs",
    "Titular": "Starter",
    "Titular · Capitán": "Starter · Captain",
    "Todo el contenido publicado en esta página se ofrece de forma gratuita e informativa. No está permitido redistribuir, copiar ni reutilizar el contenido original sin autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.": "All content published on this page is offered for free and for informational purposes. Redistributing, copying, or reusing the original content without express authorization from ZC26 is not allowed. The information is provided without warranties and may be updated without prior notice.",
    "Todos los horarios corresponden a la hora estándar de Sudamérica": "All times correspond to South American standard time",
    "Todos los horarios corresponden a la hora estándar regional": "All times correspond to the regional standard time",
    "Torneo virtual \"ZC26 AUGT8\", manejado por el equipo del soporte": "Virtual tournament \"ZC26 AUGT8\", managed by the support team",
    "TR:": "RC:",
    "Términos de uso": "Terms of use",
    "Títulos:": "Titles:",
    "Ver completo": "View full",
    "Ver estadisticas": "View statistics",
    "Versión 3.0.16.5": "Version 3.0.16.5",
    "Volver arriba": "Back to top",
    "Watch Game": "Watch Game",
    "WIN LEVIATAN ESPORT": "LEVIATAN ESPORT WIN",
    "winner": "winner",
    "YouTube": "YouTube",
    "Z. Jack": "Z. Jack",
    "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)": "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)",
    "ZC26 - Brawl Stars Championship": "ZC26 - Brawl Stars Championship",
    "ZC26 1v1 Edición 4 · 3er y 4to Lugar": "ZC26 1v1 Edition 4 · 3rd and 4th Place",
    "ZC26 1v1 Edición 4 · Gran Final": "ZC26 1v1 Edition 4 · Grand Final",
    "ZC26 1v1 Edición 4 · Ronda 1": "ZC26 1v1 Edition 4 · Round 1",
    "ZC26 1v1 Edición 4 · Ronda 2": "ZC26 1v1 Edition 4 · Round 2",
    "ZC26 1v1 Edición 4 · Semifinal": "ZC26 1v1 Edition 4 · Semifinal",
    "ZC26 1v1 · 3er y 4to Lugar": "ZC26 1v1 · 3rd and 4th Place",
    "ZC26 1v1 · Gran Final": "ZC26 1v1 · Grand Final",
    "ZC26 1v1 · Ronda 1": "ZC26 1v1 · Round 1",
    "ZC26 1v1 · Ronda 2": "ZC26 1v1 · Round 2",
    "ZC26 1v1 · Semifinal": "ZC26 1v1 · Semifinal",
    "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.": "ZC26 is an independent organization dedicated to the creation, development, and management of competitive Brawl Stars tournaments and events. This event is not affiliated with, sponsored, or endorsed by Supercell. All names, trademarks, characters, and in-game images belong exclusively to their respective creators and owners.",
    "ZC26 ESPORTS™": "ZC26 ESPORTS™",
    "ZC26 GRAN FINAL": "ZC26 GRAND FINAL",
    "ZC26 · 3er y 4to Lugar": "ZC26 · 3rd and 4th Place",
    "ZC26 · Gran Final": "ZC26 · Grand Final",
    "ZC26 · Semifinal": "ZC26 · Semifinal",
    "zc26.esports.official@gmail.com": "zc26.esports.official@gmail.com",
    "Zona horaria:": "Time zone:",
    "© ZC26 | Todos los derechos reservados.": "© ZC26 | All rights reserved.",
    "·": "·",
    "¿Quieres apoyar a ZC26? Con una donación desde 1 dólar a través de": "Want to support ZC26? With a donation starting from 1 dollar through",
    "Álvaro": "Álvaro",
    "Última actualización: 30 agosto, 2026": "Last update: August 30, 2026",
    "Última actualización: 6 dic, 2025": "Last update: Dec 6, 2025",
    "Última Clasificación": "Latest Ranking",
    "Último partido importa": "Last match matters",
    "ÚLTIMO PARTIDO IMPORTA": "LAST MATCH MATTERS",
    "–": "-",
    "✕": "✕"
};
