// idioma/es-es.js
// Diccionario Español (España). Clave = texto original en español (LatAm), Valor = traducción.
// Coincidencia EXACTA (recortando espacios). Cubre: interfaz completa, novedades,
// filtros/footer, etiquetas de tarjetas de jugador y combinaciones de torneo/resultado.

var ZC_LANG_ES_ES = {
    "% de Victoria": "% de Victoria",
    "0": "0",
    "0-2": "0-2",
    "0.0": "0,0",
    "0/11": "0/11",
    "08/09/26": "08/09/26",
    "1": "1",
    "1-2": "1-2",
    "104.0": "104,0",
    "11 Rondas": "11 Rondas",
    "11/11": "11/11",
    "118.4": "118,4",
    "129.9": "129,9",
    "132.5": "132,5",
    "15": "15",
    "153.1": "153,1",
    "17', 26'": "17', 26'",
    "19": "19",
    "1er Lugar": "1er puesto",
    "1er lugar · 120 pts": "1er puesto · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 0 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 0 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 2 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 2 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 4 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 4 · 120 pts",
    "1st": "1º",
    "1st Champion": "1er campeón",
    "2": "2",
    "2-1": "2-1",
    "20": "20",
    "20'": "20'",
    "25%": "25 %",
    "26": "26",
    "27": "27",
    "2do Lugar": "2º puesto",
    "2do lugar · 80 pts": "2º puesto · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 6 - 4 · 80 pts": "2º puesto · Sets 3 - 1 · V-D 6 - 4 · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 8 - 4 · 80 pts": "2º puesto · Sets 3 - 1 · V-D 8 - 4 · 80 pts",
    "2nd": "2º",
    "2nd Runner-Up": "Tercer puesto",
    "3": "3",
    "34": "34",
    "34'": "34'",
    "3er Lugar": "3er puesto",
    "3er lugar · 105 pts": "3er puesto · 105 pts",
    "3er lugar · 50 pts": "3er puesto · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 6 - 2 · 50 pts": "3er puesto · Sets 3 - 1 · V-D 6 - 2 · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 7 - 2 · 50 pts": "3er puesto · Sets 3 - 1 · V-D 7 - 2 · 50 pts",
    "3er lugar · Sets 3 - 2 · PG-PP 7 - 6 · 50 pts": "3er puesto · Sets 3 - 2 · V-D 7 - 6 · 50 pts",
    "3er y 4to Lugar": "3er y 4º puesto",
    "3er-4to Lugar": "3er-4º puesto",
    "3rd-4th Place": "3.º y 4.º puesto",
    "3rd-4th place": "3er-4º puesto",
    "4to Lugar": "4º puesto",
    "4to lugar · 100 pts": "4º puesto · 100 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 4 - 4 · 45 pts": "4º puesto · Sets 2 - 2 · V-D 4 - 4 · 45 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 5 - 4 · 45 pts": "4º puesto · Sets 2 - 2 · V-D 5 - 4 · 45 pts",
    "5.8": "5,8",
    "6.0": "6,0",
    "60": "60",
    "7.1": "7,1",
    "7.6": "7,6",
    "75%": "75 %",
    "8'": "8'",
    "8.6": "8,6",
    "80.8": "80,8",
    "81": "81",
    "9": "9",
    "9.4": "9,4",
    "94.8": "94,8",
    "98.0": "98,0",
    "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aporte al equipo.": "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aportación al equipo.",
    "Abrir menú": "Abrir menú",
    "Actividad": "Actividad",
    "Activo": "Activo",
    "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competencia.": "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competición.",
    "Agradecemos la participación de todos los competidores y les invitamos a mantenerse atentos a las próximas ediciones.": "Agradecemos la participación de todos los competidores y os invitamos a permanecer atentos a las próximas ediciones.",
    "Al conseguir los créditos necesarios, se abrirá una pantalla especial donde se mostrarán los personajes disponibles. Al tocar la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.": "Al conseguir los créditos necesarios, se abrirá una pantalla especial en la que se mostrarán los personajes disponibles. Al pulsar en la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.",
    "Alineaciones": "Alineaciones",
    "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.": "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.",
    "Apoyamos y síguenos en nuestras redes sociales": "Apóyanos y síguenos en nuestras redes sociales",
    "ASIA": "ASIA",
    "Argentina": "Argentina",
    "As de Combate": "As de Combate",
    "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatorio.": "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatório.",
    "Asist.:": "Asistencias:",
    "Asistencias": "Asistencias",
    "Así se jugó la final: Leviatán se impuso 3-1 en los mapas": "Así se jugó la final: Leviatán se impuso por 3-1 en los mapas",
    "Ataques": "Ataques",
    "Aug 8, 26": "8 de ago., 26",
    "Aún no hay estadísticas de defensa registradas para este partido.": "Aún no hay estadísticas de defensa registradas para este partido.",
    "Balance de mapas o modos ganados y perdidos.": "Balance de mapas o modos ganados y perdidos.",
    "Balance de sets ganados y perdidos en la competencia.": "Balance de sets ganados y perdidos en la competencia.",
    "Baneos globales": "Vetos globales",
    "Belle rock": "Roca de Belle",
    "Bolivia": "Bolivia",
    "Brasil": "Brasil",
    "Capacidad para controlar el mapa y mantener buena posición durante la partida.": "Capacidad para controlar el mapa y mantener buena posición durante la partida.",
    "Capacidad para sobrevivir y reducir el daño recibido en combate.": "Capacidad para sobrevivir y reducir el daño recibido en combate.",
    "Chile": "Chile",
    "Colombia": "Colombia",
    "Contribución en la captura o cumplimiento de los objetivos del modo.": "Contribución en la captura o cumplimiento de los objetivos del modo.",
    "Control de Zona y Posicionamiento": "Control de Zona y Posicionamiento",
    "EMEA (Europa, Medio Oriente y África)": "EMEA (Europa, Medio Oriente y África)",
    "Ecuador": "Ecuador",
    "Eficiencia en Combate (K/D/A)": "Eficiencia en Combate (K/D/A)",
    "El Salvador": "El Salvador",
    "España": "España",
    "Ghana": "Ghana",
    "Gran Maestro de Combate": "Gran Maestro de Combate",
    "Guatemala": "Guatemala",
    "Habilidades": "Habilidades",
    "Honduras": "Honduras",
    "Impacto y Uso del Súper": "Impacto y Uso del Súper",
    "K/D/A": "K/D/A",
    "L. Puppies Represent": "L. Puppies Represent",
    "LEVIATÁN ESPORTS se coronó campeón de la Gran Final ZC26 el 09/08/26 tras vencer 3-1 a Cachorritas repres (LPR). Título obtenido con la alineación de Julio (capitán), iXLCross y JOAR.": "LEVIATÁN ESPORTS se coronó campeón de la Gran Final ZC26 el 09/08/26 tras vencer 3-1 a Cachorritas repres (LPR). Título obtenido con la alineación de Julio (capitán), iXLCross y JOAR.",
    "Leviatán Esports": "Leviatán Esports",
    "Maestro de Combate": "Maestro de Combate",
    "Mapas": "Mapas",
    "Mayor descenso": "Mayor descenso",
    "Mejor clasificación": "Mejor clasificación",
    "Más puntos conseguidos": "Más puntos conseguidos",
    "Más puntos perdidos": "Más puntos perdidos",
    "México": "México",
    "Norteamérica": "Norteamérica",
    "Objetivos": "Objetivos",
    "Perú": "Perú",
    "Pool": "Pool",
    "Porcentaje de Victorias": "Porcentaje de Victorias",
    "Porcentaje de partidas o sets ganados sobre el total jugado.": "Porcentaje de partidas o sets ganados sobre el total jugado.",
    "Potencial": "Potencial",
    "Promedio de Puntos por Torneo": "Promedio de Puntos por Torneo",
    "Pts/Torneo": "Pts/Torneo",
    "Puntos obtenidos en promedio por cada torneo disputado.": "Puntos obtenidos en promedio por cada torneo disputado.",
    "Qué tan efectivo es usando su habilidad Súper en el momento correcto.": "Qué tan efectivo es usando su habilidad Súper en el momento correcto.",
    "Qué tan variado y flexible es su repertorio de personajes al draftear.": "Qué tan variado y flexible es su repertorio de personajes al draftear.",
    "Rango Mítico": "Rango Mítico",
    "Relación entre eliminaciones, muertes y asistencias en combate.": "Relación entre eliminaciones, muertes y asistencias en combate.",
    "Reputación Int.": "Reputación Int.",
    "Récord de Mapas/Modos (PG-PP)": "Récord de Mapas/Modos (PG-PP)",
    "Récord de Sets (G-P)": "Récord de Sets (G-P)",
    "Sudamérica": "Sudamérica",
    "Superviv.": "Superviv.",
    "Supervivencia y Mitigación de Daño": "Supervivencia y Mitigación de Daño",
    "Súper": "Súper",
    "Toma de Objetivos del Modo de Juego": "Toma de Objetivos del Modo de Juego",
    "Venezuela": "Venezuela",
    "Versatilidad de Pool (Drafteo)": "Versatilidad de Pool (Drafteo)",
    "Victorias %": "Victorias %",
    "Zona": "Zona",
    "belle y spike": "Belle y Spike",
    "Bibi y Nori": "Bibi y Nori",
    "Brawl Ball": "Balón Brawl",
    "Brawl Stars Oficial": "Brawl Stars Oficial",
    "Brawl Stars · Agosto 8 de 2026": "Brawl Stars · 8 de agosto de 2026",
    "BRAWLER BLAST": "EXPLOSIÓN BRAWLER",
    "Brawlers principales": "Brawlers principales",
    "BSC, AUG 8": "BSC, 8 DE AGOSTO",
    "Buscar por nombre, ID o país...": "Buscar por nombre, ID o país...",
    "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, como puntos de fuerza, gadgets, habilidades estelares, engranajes o hipercargas. Siempre se asegurará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.": "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, tales como puntos de fuerza, artilugios, habilidades estelares, engranajes o hipercargas. Siempre se garantizará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.",
    "Calificaciones de los jugadores (0/11) basadas en los datos de los partidos": "Puntuaciones de los jugadores (0/11) basadas en los datos de los partidos",
    "Calificación del jugador": "Valoración del jugador",
    "Campeones a lo largo de los torneos ZC26": "Campeones a lo largo de los torneos ZC26",
    "Campeón": "Campeón",
    "Campeón · 500 pts · +25 Estelar (Set 1)": "Campeón · 500 pts · +25 Estelar (Set 1)",
    "Campeón · 500 pts · +25 Estelar (Set 3)": "Campeón · 500 pts · +25 Estelar (Set 3)",
    "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP": "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP",
    "Campeón · Suplente (no disputó rondas)": "Campeón · Suplente (no disputó rondas)",
    "Champion": "Campeón",
    "Clasificación actual": "Clasificación actual",
    "Clasificatoria": "Clasificatoria",
    "Coach": "Entrenador",
    "COMENTARIOS": "COMENTARIOS",
    "Con estos resultados, la tabla general de posiciones quedó encabezada por Leviatán Esports en el primer lugar, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.": "Con estos resultados, la tabla general de clasificación quedó encabezada por Leviatán Esports en el primer puesto, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.",
    "Contacto": "Contacto",
    "Contacto comercial y soporte:": "Contacto comercial y asistencia:",
    "Contribucion": "Contribución",
    "Contribución total": "Contribución total",
    "Copyrights © ZC ESPORTS 2026": "Derechos de autor © ZC ESPORTS 2026",
    "CREDITOS": "CRÉDITOS",
    "Cronología": "Cronología",
    "Créditos aprox.": "Créditos aprox.",
    "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.": "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.",
    "Datos de Brawl Stars": "Datos de Brawl Stars",
    "Datos destacados": "Datos destacados",
    "Defensas": "Defensas",
    "Descenso": "Descenso",
    "Después de ese evento, nos tomamos un tiempo fuera de las canchas para planificar todo con calma, pero la espera terminó y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta oportunidad, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.": "Después de aquel evento, nos tomamos un tiempo fuera de las pistas para planificar todo con calma, pero la espera ha terminado y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta ocasión, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.",
    "Discord": "Discord",
    "doble swoosh": "Doble Swoosh",
    "DPS:": "Daño por segundo (DPS):",
    "Edición 4": "Edición 4",
    "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se jugó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.": "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se disputó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.",
    "El encuentro terminó.": "El encuentro ha terminado.",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast": "El sistema del Camino Starr será sustituido por una nueva mecánica llamada Explosión Brawler",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de manera aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.": "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de forma aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.",
    "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su final, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competencia estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.": "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su fin, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competición estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.",
    "Eliminaciones (Kills)": "Eliminaciones (Bajas)",
    "EMEA": "EMEA",
    "En el segundo mapa, Roca de Belle, el conjunto rival logró responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un categórico dos a cero.": "En el segundo mapa, Roca de Belle, el conjunto rival consiguió responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un rotundo dos a cero.",
    "Equipo": "Equipo",
    "Equipo de Apoyo": "Equipo de apoyo",
    "Estado": "Estado",
    "Escalafón": "Escalafón",
    "Estadísticas": "Estadísticas",
    "Estadísticas clave": "Estadísticas clave",
    "Estadísticas del partido": "Estadísticas del partido",
    "Estadísticas generales del partido": "Estadísticas generales del partido",
    "Estadísticas y rendimiento competitivo": "Estadísticas y rendimiento competitivo",
    "Estimada comunidad, nos alegra mucho ponernos en contacto con ustedes para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordarán, en la última edición el equipo de Levantan Esports se quedó con el primer lugar tras una excelente participación.": "Estimada comunidad, nos alegra enormemente ponernos en contacto con vosotros para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordaréis, en la última edición el equipo de Levantan Esports se hizo con la primera plaza tras una excelente participación.",
    "Eventos:": "Eventos:",
    "Faltas": "Faltas",
    "Filtro": "Filtro",
    "Filtros": "Filtros",
    "Fin": "Fin",
    "Finalized": "Finalizado",
    "Finished": "Terminado",
    "Ganancias aprox.": "Ganancias aprox.",
    "Gem Grab": "Atrapagemas",
    "Gmail": "Gmail",
    "GRAN FINAL": "GRAN FINAL",
    "Gran Final": "Gran Final",
    "Gran Final 🏆": "Gran Final 🏆",
    "Heist": "Atraco",
    "Highlights": "Mejores momentos",
    "Historias destacadas": "Historias destacadas",
    "Home": "Inicio",
    "HOME": "INICIO",
    "IDs alternos": "ID alternativos",
    "Imagen no disponible": "Imagen no disponible",
    "Inactivo": "Inactivo",
    "Información": "Información",
    "Información del jugador": "Información del jugador",
    "Información general": "Información general",
    "iXCross": "iXCross",
    "iXLCross": "iXLCross",
    "JOAR": "JOAR",
    "Juanjo": "Juanjo",
    "Juanjoxd": "Juanjoxd",
    "Jugador": "Jugador",
    "Jugador Sorpresa": "Jugador revelación",
    "Julio": "Julio",
    "Juliocr36D": "Juliocr36D",
    "Kills:": "Bajas:",
    "Knockout": "Noqueo",
    "L. Puppies Represent · Titulares": "L. Puppies Represent · Titulares",
    "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competencia intensa donde solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.": "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competición intensa en la que tan solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.",
    "La ZC26 vuelve este septiembre": "La ZC26 vuelve este septiembre",
    "leafy bushes": "Arbustos Frondosos",
    "LEV": "LEV",
    "LEV WINNER": "VICTORIA DE LEV",
    "LEVIATÁN ESPORT · Titulares": "LEVIATÁN ESPORT · Titulares",
    "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 Agosto": "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 de agosto",
    "Lo más destacado del ranking": "Lo más destacado de la clasificación",
    "Logros": "Logros",
    "Los invitamos a ponerse de acuerdo con sus compañeros, armar sus alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que manténganse atentos a los anuncios.": "Os invitamos a poneros de acuerdo con vuestros compañeros, montar vuestras alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que estad muy atentos aos anuncios.",
    "LPR": "LPR",
    "Lugar:": "Lugar:",
    "MATCHES, AUG 8": "PARTIDOS, 8 DE AGOSTO",
    "Mayor a menor": "De mayor a menor",
    "Mayor bajada": "Mayor bajada",
    "Mayor subida": "Mayor subida",
    "Mejor Clasificación": "Mejor clasificación",
    "Mejor contribución": "Mejor contribución",
    "Mejor jugada": "Mejor jugada",
    "MEJOR JUGADA": "MEJOR JUGADA",
    "Menor a mayor": "De menor a mayor",
    "Modalidad: 3 vs 3 · Bo5 · Tier S": "Modalidad: 3 vs 3 · Md5 · Nivel S",
    "Momentos de la BSC de la ZC26™": "Momentos de la BSC de la ZC26™",
    "Mostrar Clasificación completa": "Mostrar clasificación completa",
    "Mostrar menos": "Mostrar menos",
    "Mostrar más": "Mostrar más",
    "mostrar más": "mostrar más",
    "Movimiento": "Movimiento",
    "MVP:": "Mejor Jugador (MVP):",
    "Más info.": "Más información",
    "Más información sobre": "Más información sobre",
    "Más partidos": "Más partidos",
    "MÁS ZC26": "MÁS ZC26",
    "N/A": "N/D",
    "NA": "NA",
    "Nacaru": "Nacaru",
    "Nacimiento": "Nacimiento",
    "Nacionalidad": "Nacionalidad",
    "Nada": "Nada",
    "NEW": "NUEVO",
    "Ninja": "Ninja",
    "No hace falta ser un experto en competencias para sumarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.": "No hace falta ser un experto en competiciones para apuntarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.",
    "No hay logros registrados": "No hay logros registrados",
    "No se encontró ningún jugador con estos filtros.": "No se ha encontrado ningún jugador con estos filtros.",
    "No se encontró ningún jugador.": "No se ha encontrado ningún jugador.",
    "No se pudo cargar el archivo de idioma:": "No se ha podido cargar el archivo de idioma:",
    "Nueva clasificación más alta": "Nueva clasificación más alta",
    "Nuevo": "Nuevo",
    "Ocultar Clasificación completa": "Ocultar clasificación completa",
    "Orden": "Orden",
    "Organización del Evento: ZC26 BSC (Brawl Stars Championship)": "Organización del evento: ZC26 BSC (Campeonato de Brawl Stars)",
    "Otro punto en el que pusimos mucho esfuerzo fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.": "Otro aspecto en el que pusimos mucho empeño fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.",
    "Para esta edición decidimos renovar varias cosas. Incorporamos nuevas reglas y mecánicas de juego que buscan equilibrar la cancha para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.": "Para esta edición hemos decidido renovar varias cosas. Hemos incorporado nuevas reglas y mecánicas de juego que buscan equilibrar el terreno para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.",
    "Partidas (PG-PP):": "Partidas (V-D):",
    "Partidas recientes": "Partidas recientes",
    "Partners": "Colaboradores",
    "PARTNERS": "COLABORADORES",
    "PayPal": "PayPal",
    "País": "País",
    "Peor clasificación": "Peor clasificación",
    "PG-PP": "V-D",
    "Player Tag / Player ID": "Etiqueta de jugador / ID de jugador",
    "Por confirmar": "Por confirmar",
    "Porcentaje de victorias": "Tasa de victorias",
    "Posiciones": "Clasificaciones",
    "Posición en el ranking": "Posición en la clasificación",
    "Posición promedio": "Posición media",
    "PREMIOS": "PREMIOS",
    "Promedio de puntos por torneo": "Media de puntos por torneo",
    "Promedio DPS de Equipo": "Promedio de daño por segundo del equipo",
    "pts": "pts",
    "puedes obtener beneficios dentro de la comunidad.": "puedes obtener ventajas dentro de la comunidad.",
    "Punto de campeonato": "Punto de campeonato",
    "PUNTO DE CAMPEONATO": "PUNTO DE CAMPEONATO",
    "Puntos totales:": "Puntos totales:",
    "Ranking": "Clasificación",
    "RANKING": "CLASIFICACIÓN",
    "Reconocimientos especiales": "Reconocimientos especiales",
    "Redes oficiales:": "Redes oficiales:",
    "Redes sociales": "Redes sociales",
    "Región": "Región",
    "Regresa la ZC26 Brawl Stars este mes de septiembre": "La ZC26 de Brawl Stars vuelve este mes de septiembre",
    "Regresar": "Volver",
    "Restablecer filtros": "Restablecer filtros",
    "RESUMEN AGOSTO": "RESUMEN DE AGOSTO",
    "Rol": "Rol",
    "Ronda 1": "Ronda 1",
    "Ronda 2": "Ronda 2",
    "Rondas Ganadas (Sets)": "Rondas ganadas (Sets)",
    "Rondas:": "Rondas:",
    "Récord de mapas/modos (PG-PP)": "Historial de mapas/modos (V-D)",
    "Récord de sets (G-P)": "Historial de sets (V-D)",
    "SA": "SA",
    "SALON DE LA FAMA": "SALÓN DE LA FAMA",
    "Salón de la fama": "Salón de la Fama",
    "Salón de la Fama": "Salón de la Fama",
    "Sanciones": "Sanciones",
    "Se actualiza con cada contribucion a ZC26": "Se actualiza con cada contribución a la ZC26",
    "Se actualiza con cada torneo de ZC26": "Se actualiza con cada torneo de la ZC26",
    "Según los datos de los partidos": "Según los datos de las partidas",
    "Seleccion completa": "Selección completa",
    "Semifinal": "Semifinal",
    "Servidores Globales, Brawl Stars": "Servidores globales, Brawl Stars",
    "Set Marcado:": "Set anotado:",
    "Sets": "Sets",
    "Sets (G-P):": "Sets (V-D):",
    "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como corrección de nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor contáctanos a través de los medios oficiales indicados arriba.": "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como la corrección del nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor, ponte en contacto con nosotros a través de los medios oficiales indicados arriba.",
    "Silenciar sonidos": "Silenciar sonidos",
    "Sin partidas registradas": "Sin partidas registradas",
    "Subcampeón": "Subcampeón",
    "Subcampeón · 250 pts": "Subcampeón · 250 pts",
    "Subcampeón · 250 pts · +25 Estelar (Set 2)": "Subcampeón · 250 pts · +25 Estelar (Set 2)",
    "Subida": "Ascenso",
    "Suplente · LEV": "Suplente · LEV",
    "Suplentes": "Suplentes",
    "Sí": "Sí",
    "TA:": "TA:",
    "Taikisha, elegido MVP de la Gran Final": "Taikisha, elegido Mejor Jugador de la Gran Final",
    "TAIKISHA, MVP": "TAIKISHA, MVP",
    "Taikisha, MVP 🏆": "Taikisha, Mejor Jugador 🏆",
    "Tarjetas Amarillas": "Tarjetas amarillas",
    "Tarjetas Rojas": "Tarjetas rojas",
    "TikTok": "TikTok",
    "tire maniacs": "Locura de Neumáticos",
    "Titular": "Titular",
    "Titular · Capitán": "Titular · Capitán",
    "Todo el contenido publicado en esta página se ofrece de forma gratuita e informativa. No está permitido redistribuir, copiar ni reutilizar el contenido original sin autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.": "Todo el contenido publicado en esta página se ofrece de forma gratuita y con carácter informativo. No está permitido redistribuir, copiar ni reutilizar el contenido original sin la autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.",
    "Todos los horarios corresponden a la hora estándar de Sudamérica": "Todos los horarios corresponden a la hora estándar de Sudamérica",
    "Todos los horarios corresponden a la hora estándar regional": "Todos los horarios corresponden a la hora estándar regional",
    "Torneo virtual \"ZC26 AUGT8\", manejado por el equipo del soporte": "Torneo virtual \"ZC26 AUGT8\", gestionado por el equipo de soporte",
    "TR:": "TR:",
    "Términos de uso": "Términos de uso",
    "Títulos:": "Títulos:",
    "Ver completo": "Ver al completo",
    "Ver estadisticas": "Ver estadísticas",
    "Versión 3.0.16.5": "Versión 3.0.16.5",
    "Volver arriba": "Volver arriba",
    "Watch Game": "Ver partido",
    "WIN LEVIATAN ESPORT": "VICTORIA DE LEVIATAN ESPORT",
    "winner": "ganador",
    "YouTube": "YouTube",
    "Z. Jack": "Z. Jack",
    "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)": "ZC ESPORTS · ZC26 · BSC (Campeonato de Brawl Stars)",
    "ZC26 - Brawl Stars Championship": "ZC26 - Campeonato de Brawl Stars",
    "ZC26 1v1 Edición 4 · 3er y 4to Lugar": "ZC26 1v1 Edición 4 · 3er y 4º puesto",
    "ZC26 1v1 Edición 4 · Gran Final": "ZC26 1v1 Edición 4 · Gran Final",
    "ZC26 1v1 Edición 4 · Ronda 1": "ZC26 1v1 Edición 4 · Ronda 1",
    "ZC26 1v1 Edición 4 · Ronda 2": "ZC26 1v1 Edición 4 · Ronda 2",
    "ZC26 1v1 Edición 4 · Semifinal": "ZC26 1v1 Edición 4 · Semifinal",
    "ZC26 1v1 · 3er y 4to Lugar": "ZC26 1v1 · 3er y 4º puesto",
    "ZC26 1v1 · Gran Final": "ZC26 1v1 · Gran Final",
    "ZC26 1v1 · Ronda 1": "ZC26 1v1 · Ronda 1",
    "ZC26 1v1 · Ronda 2": "ZC26 1v1 · Ronda 2",
    "ZC26 1v1 · Semifinal": "ZC26 1v1 · Semifinal",
    "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.": "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.",
    "ZC26 ESPORTS™": "ZC26 ESPORTS™",
    "ZC26 GRAN FINAL": "ZC26 GRAN FINAL",
    "ZC26 · 3er y 4to Lugar": "ZC26 · 3er y 4º puesto",
    "ZC26 · Gran Final": "ZC26 · Gran Final",
    "ZC26 · Semifinal": "ZC26 · Semifinal",
    "zc26.esports.official@gmail.com": "zc26.esports.official@gmail.com",
    "Zona horaria:": "Zona horaria:",
    "© ZC26 | Todos los derechos reservados.": "© ZC26 | Todos los derechos reservados.",
    "·": "·",
    "¿Quieres apoyar a ZC26? Con una donación desde 1 dólar a través de": "¿Quieres apoyar a ZC26? Con una donación a partir de 1 dólar a través de",
    "Álvaro": "Álvaro",
    "Última actualización: 30 agosto, 2026": "Última actualización: 30 de agosto de 2026",
    "Última actualización: 6 dic, 2025": "Última actualización: 6 de dic. de 2025",
    "Última Clasificación": "Última clasificación",
    "Último partido importa": "El último partido importa",
    "ÚLTIMO PARTIDO IMPORTA": "EL ÚLTIMO PARTIDO IMPORTA",
    "–": "-",
    "✕": "✕"
};
