// idioma/es-es.js
// Diccionario Español (España). Clave = texto original en español (LatAm), Valor = traducción.
// Coincidencia EXACTA (recortando espacios).

var ZC_LANG_ES_ES = {
    "% de Victoria": "% de Victoria",
    "0": "0",
    "0-2": "0-2",
    "0.0": "0,0",
    "0/11": "0/11",
    "08/09/26": "08/09/26",
    "1": "1",
    "1 ago 2026": "1 ago 2026",
    "1-2": "1-2",
    "104.0": "104,0",
    "11 Rondas": "11 Rondas",
    "11/11": "11/11",
    "118.4": "118,4",
    "129.9": "129,9",
    "132.5": "132,5",
    "15": "15",
    "153.1": "153,1",
    "17', 26'": "17', 26'",
    "19": "19",
    "1er Lugar": "1er puesto",
    "1er lugar · 120 pts": "1er puesto · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 0 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 0 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 2 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 2 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 4 · 120 pts": "1er puesto · Sets 4 - 0 · V-D 9 - 4 · 120 pts",
    "1st": "1º",
    "1st Champion": "1er campeón",
    "2": "2",
    "2-1": "2-1",
    "20": "20",
    "20'": "20'",
    "25%": "25 %",
    "26": "26",
    "27": "27",
    "27 ago 2026": "27 ago 2026",
    "2do Lugar": "2º puesto",
    "2do lugar · 80 pts": "2º puesto · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 6 - 4 · 80 pts": "2º puesto · Sets 3 - 1 · V-D 6 - 4 · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 8 - 4 · 80 pts": "2º puesto · Sets 3 - 1 · V-D 8 - 4 · 80 pts",
    "2nd": "2º",
    "2nd Runner-Up": "Tercer puesto",
    "3": "3",
    "30 ago 2026": "30 ago 2026",
    "34": "34",
    "34'": "34'",
    "3er Lugar": "3er puesto",
    "3er lugar · 105 pts": "3er puesto · 105 pts",
    "3er lugar · 50 pts": "3er puesto · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 6 - 2 · 50 pts": "3er puesto · Sets 3 - 1 · V-D 6 - 2 · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 7 - 2 · 50 pts": "3er puesto · Sets 3 - 1 · V-D 7 - 2 · 50 pts",
    "3er lugar · Sets 3 - 2 · PG-PP 7 - 6 · 50 pts": "3er puesto · Sets 3 - 2 · V-D 7 - 6 · 50 pts",
    "3er y 4to Lugar": "3er y 4º puesto",
    "3er-4to Lugar": "3er-4º puesto",
    "3rd-4th Place": "3.º y 4.º puesto",
    "3rd-4th place": "3er-4º puesto",
    "4to Lugar": "4º puesto",
    "4to lugar · 100 pts": "4º puesto · 100 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 4 - 4 · 45 pts": "4º puesto · Sets 2 - 2 · V-D 4 - 4 · 45 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 5 - 4 · 45 pts": "4º puesto · Sets 2 - 2 · V-D 5 - 4 · 45 pts",
    "5 ago 2026": "5 ago 2026",
    "5.8": "5,8",
    "6.0": "6,0",
    "60": "60",
    "7.1": "7,1",
    "7.6": "7,6",
    "75%": "75 %",
    "8 ago 2026": "8 ago 2026",
    "8'": "8'",
    "8.6": "8,6",
    "80.8": "80,8",
    "81": "81",
    "9": "9",
    "9.4": "9,4",
    "94.8": "94,8",
    "98.0": "98,0",
    "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aporte al equipo.": "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aportación al equipo.",
    "Abrir menú": "Abrir menú",
    "Actividad": "Actividad",
    "Activo": "Activo",
    "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competencia.": "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competición.",
    "Agradecemos la participación de todos los competidores y les invitamos a mantenerse atentos a las próximas ediciones.": "Agradecemos la participación de todos los competidores y os invitamos a permanecer atentos a las próximas ediciones.",
    "Ajuste de ponderación por tipo de evento:": "Ajuste de ponderación por tipo de evento:",
    "Al conseguir los créditos necesarios, se abrirá una pantalla especial donde se mostrarán los personajes disponibles. Al tocar la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.": "Al conseguir los créditos necesarios, se abrirá una pantalla especial en la que se mostrarán los personajes disponibles. Al pulsar en la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.",
    "Alineaciones": "Alineaciones",
    "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.": "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.",
    "Apoyamos y síguenos en nuestras redes sociales": "Apóyanos y síguenos en nuestras redes sociales",
    "Arranca la nueva temporada: así se reinicia la puntuación de cada jugador": "Arranca la nueva temporada: así se reinicia la puntuación de cada jugador",
    "As Combat": "Combate As",
    "ASIA": "ASIA",
    "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatorio.": "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatório.",
    "Asist.:": "Asistencias:",
    "Asistencias": "Asistencias",
    "Así se jugó la final: Leviatán se impuso 3-1 en los mapas": "Así se jugó la final: Leviatán se impuso por 3-1 en los mapas",
    "Ataques": "Ataques",
    "Aug 8, 26": "8 de ago., 26",
    "Aún no hay estadísticas de defensa registradas para este partido.": "Aún no hay estadísticas de defensa registradas para este partido.",
    "Balance global interregional: elimina el sesgo regional. Un equipo de LATAM o Asia tiene exactamente la misma oportunidad de escalar al Top 1 Global que un equipo de Europa o Norteamérica al ganar torneos de similar categoría.": "Balance global interregional: elimina el sesgo regional. Un equipo de LATAM o Asia tiene exactamente la misma oportunidad de escalar al Top 1 Global que un equipo de Europa o Norteamérica al ganar torneos de similar categoría.",
    "Baneos globales": "Vetos globales",
    "Belle rock": "Roca de Belle",
    "belle y spike": "Belle y Spike",
    "Beneficios para el ecosistema Esports de Brawl Stars": "Beneficios para el ecosistema Esports de Brawl Stars",
    "Bibi y Nori": "Bibi y Nori",
    "Brawl Ball": "Balón Brawl",
    "Brawl Stars Oficial": "Brawl Stars Oficial",
    "Brawl Stars · Agosto 8 de 2026": "Brawl Stars · 8 de agosto de 2026",
    "BRAWLER BLAST": "EXPLOSIÓN BRAWLER",
    "Brawlers principales": "Brawlers principales",
    "BSC, AUG 8": "BSC, 8 DE AGOSTO",
    "Buscar por nombre, ID o país...": "Buscar por nombre, ID o país...",
    "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, como puntos de fuerza, gadgets, habilidades estelares, engranajes o hipercargas. Siempre se asegurará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.": "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, tales como puntos de fuerza, artilugios, habilidades estelares, engranajes o hipercargas. Siempre se garantizará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.",
    "Calificaciones de los jugadores (0/11) basadas en los datos de los partidos": "Puntuaciones de los jugadores (0/11) basadas en los datos de los partidos",
    "Calificación del jugador": "Valoración del jugador",
    "Campeones a lo largo de los torneos ZC26": "Campeones a lo largo de los torneos ZC26",
    "Campeón": "Campeón",
    "Campeón · 500 pts · +25 Estelar (Set 1)": "Campeón · 500 pts · +25 Estelar (Set 1)",
    "Campeón · 500 pts · +25 Estelar (Set 3)": "Campeón · 500 pts · +25 Estelar (Set 3)",
    "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP": "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP",
    "Campeón · Suplente (no disputó rondas)": "Campeón · Suplente (no disputó rondas)",
    "Cero penalizaciones por inactividad injusta: el ranking no degrada puntos artificialmente por el paso del tiempo, eliminando la necesidad de competir en eventos menores solo para \"mantener la posición\".": "Cero penalizaciones por inactividad injusta: el ranking no degrada puntos artificialmente por el paso del tiempo, eliminando la necesidad de competir en eventos menores solo para \"mantener la posición\".",
    "Champion": "Campeón",
    "Claridad en la selección de Seeds: permite a los organizadores de torneos (TOs) sembrar los brackets de torneos 1v1 y 3v3 de forma justa, evitando cruces de alto nivel en las primeras rondas de una clasificatoria.": "Claridad en la selección de Seeds: permite a los organizadores de torneos (TOs) sembrar los brackets de torneos 1v1 y 3v3 de forma justa, evitando cruces de alto nivel en las primeras rondas de una clasificatoria.",
    "Clasificación actual": "Clasificación actual",
    "Clasificación ZC26 - Últimas noticias": "Clasificación ZC26 - Últimas noticias",
    "Coach": "Entrenador",
    "COMENTARIOS": "COMENTARIOS",
    "Con estos resultados, la tabla general de posiciones quedó encabezada por Leviatán Esports en el primer lugar, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.": "Con estos resultados, la tabla general de clasificación quedó encabezada por Leviatán Esports en el primer puesto, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.",
    "Contacto": "Contacto",
    "Contacto comercial y soporte:": "Contacto comercial y asistencia:",
    "Contribucion": "Contribución",
    "Contribución total": "Contribución total",
    "Copyrights © ZC ESPORTS 2026": "Derechos de autor © ZC ESPORTS 2026",
    "CREDITOS": "CRÉDITOS",
    "Cronología": "Cronología",
    "Créditos aprox.": "Créditos aprox.",
    "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.": "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.",
    "Datos de Brawl Stars": "Datos de Brawl Stars",
    "Datos destacados": "Datos destacados",
    "Defensas": "Defensas",
    "Derrotas": "Derrotas",
    "Descenso": "Descenso",
    "Después de ese evento, nos tomamos un tiempo fuera de las canchas para planificar todo con calma, pero la espera terminó y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta oportunidad, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.": "Después de aquel evento, nos tomamos un tiempo fuera de las pistas para planificar todo con calma, pero la espera ha terminado y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta ocasión, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.",
    "Discord": "Discord",
    "doble swoosh": "Doble Swoosh",
    "Donde dr es la diferencia de puntos entre ambos competidores: dr = [P_antes del Equipo A − P_antes del Equipo B].": "Donde dr es la diferencia de puntos entre ambos competidores: dr = [P_antes del Equipo A − P_antes del Equipo B].",
    "DPS:": "Daño por segundo (DPS):",
    "Edición 4": "Edición 4",
    "Ejemplo:": "Ejemplo:",
    "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se jugó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.": "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se disputó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.",
    "El encuentro terminó.": "El encuentro ha terminado.",
    "el Equipo A tiene 1300 puntos y vence en una Clasificatoria Abierta al Equipo B, que tiene 1500 puntos.": "el Equipo A tiene 1300 puntos y vence en una Clasificatoria Abierta al Equipo B, que tiene 1500 puntos.",
    "El método Elo suma o resta puntos al total acumulado de cada jugador o equipo en función de los resultados de sus partidas (en lugar de promediar). Los puntos ganados o perdidos se determinan según el nivel del rival, garantizando que vencer a un equipo o jugador de rango superior otorgue una recompensa significativamente mayor.": "El método Elo suma o resta puntos al total acumulado de cada jugador o equipo en función de los resultados de sus partidas (en lugar de promediar). Los puntos ganados o perdidos se determinan según el nivel del rival, garantizando que vencer a un equipo o jugador de rango superior otorgue una recompensa significativamente mayor.",
    "El nuevo modelo para calcular el Ranking Mundial de Brawl Stars (BWR) fue desarrollado tras analizar el rendimiento de los equipos en modos 1v1 y 3v3 durante múltiples temporadas, probando y discutiendo diversos algoritmos.": "El nuevo modelo para calcular el Ranking Mundial de Brawl Stars (BWR) fue desarrollado tras analizar el rendimiento de los equipos en modos 1v1 y 3v3 durante múltiples temporadas, probando y discutiendo diversos algoritmos.",
    "El objetivo principal es contar con un sistema intuitivo, transparente y preciso para medir la fuerza real de los jugadores y clubes en la escena competitiva, garantizando oportunidades equitativas para que las organizaciones de todas las regiones (LATAM, Europa, NA, Asia, etc.) asciendan en la tabla global.": "El objetivo principal es contar con un sistema intuitivo, transparente y preciso para medir la fuerza real de los jugadores y clubes en la escena competitiva, garantizando oportunidades equitativas para que las organizaciones de todas las regiones (LATAM, Europa, NA, Asia, etc.) asciendan en la tabla global.",
    "El sistema Camino Starr será reemplazado por Brawler Blast": "El sistema Camino Starr será reemplazado por Brawler Blast",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast": "El sistema del Camino Starr será sustituido por una nueva mecánica llamada Explosión Brawler",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de manera aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.": "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de forma aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.",
    "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su final, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competencia estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.": "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su fin, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competición estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.",
    "Eliminaciones (Kills)": "Eliminaciones (Bajas)",
    "EMEA": "EMEA",
    "En el segundo mapa, Roca de Belle, el conjunto rival logró responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un categórico dos a cero.": "En el segundo mapa, Roca de Belle, el conjunto rival consiguió responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un rotundo dos a cero.",
    "Equipo": "Equipo",
    "Equipo A: P = 1300 + 25 × (1 − (1 / (10^(−(1300−1500)/600) + 1)))": "Equipo A: P = 1300 + 25 × (1 − (1 / (10^(−(1300−1500)/600) + 1)))",
    "Equipo B: P = 1500 + 25 × (0 − (1 / (10^(−(1500−1300)/600) + 1)))": "Equipo B: P = 1500 + 25 × (0 − (1 / (10^(−(1500−1300)/600) + 1)))",
    "Equipo de Apoyo": "Equipo de apoyo",
    "Estado": "Estado",
    "Estadísticas": "Estadísticas",
    "Estadísticas clave": "Estadísticas clave",
    "Estadísticas del partido": "Estadísticas del partido",
    "Estadísticas generales del partido": "Estadísticas generales del partido",
    "Estadísticas y rendimiento competitivo": "Estadísticas y rendimiento competitivo",
    "Estimada comunidad, nos alegra mucho ponernos en contacto con ustedes para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordarán, en la última edición el equipo de Levantan Esports se quedó con el primer lugar tras una excelente participación.": "Estimada comunidad, nos alegra enormemente ponernos en contacto con vosotros para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordaréis, en la última edición el equipo de Levantan Esports se hizo con la primera plaza tras una excelente participación.",
    "Eventos:": "Eventos:",
    "Exención de penalización: sin pérdida de puntos al ser eliminado en las rondas finales K.O. de eventos presenciales o Majors.": "Exención de penalización: sin pérdida de puntos al ser eliminado en las rondas finales K.O. de eventos presenciales o Majors.",
    "Faltas": "Faltas",
    "Fecha": "Fecha",
    "Filtro": "Filtro",
    "Filtros": "Filtros",
    "Fin": "Fin",
    "Finalized": "Finalizado",
    "Finished": "Terminado",
    "Ganancias aprox.": "Ganancias aprox.",
    "Gem Grab": "Atrapagemas",
    "Gmail": "Gmail",
    "GRAN FINAL": "GRAN FINAL",
    "Gran Final": "Gran Final",
    "Gran Final 🏆": "Gran Final 🏆",
    "Habilidades": "Habilidades",
    "Heist": "Atraco",
    "Highlights": "Mejores momentos",
    "Historias destacadas": "Historias destacadas",
    "Home": "Inicio",
    "HOME": "INICIO",
    "I = 05 — Showmatches o partidas de exhibición sin invitación oficial": "I = 05 — Showmatches o partidas de exhibición sin invitación oficial",
    "I = 10 — Partidas de exhibición / Scrims oficiales transmitidas": "I = 10 — Partidas de exhibición / Scrims oficiales transmitidas",
    "I = 15 — Fase de grupos de Ligas Regionales Semiprofesionales": "I = 15 — Fase de grupos de Ligas Regionales Semiprofesionales",
    "I = 25 — Clasificatorias Abiertas (Open Qualifiers) a Torneos Majors o BSC (Brawl Stars Championship)": "I = 25 — Clasificatorias Abiertas (Open Qualifiers) a Torneos Majors o BSC (Brawl Stars Championship)",
    "I = 25 — Playoffs y Finales de Ligas Regionales": "I = 25 — Playoffs y Finales de Ligas Regionales",
    "I = 35 — Fase de grupos de Torneos Internacionales / Majors hasta cuartos de final": "I = 35 — Fase de grupos de Torneos Internacionales / Majors hasta cuartos de final",
    "I = 40 — Fase de grupos de Torneos Internacionales desde cuartos de final en adelante": "I = 40 — Fase de grupos de Torneos Internacionales desde cuartos de final en adelante",
    "I = 50 — Fase final del Mundial / World Finals hasta cuartos de final": "I = 50 — Fase final del Mundial / World Finals hasta cuartos de final",
    "I = 60 — Fase final del Mundial / World Finals desde cuartos de final hasta la Gran Final": "I = 60 — Fase final del Mundial / World Finals desde cuartos de final hasta la Gran Final",
    "I:": "I:",
    "IDs alternos": "ID alternativos",
    "Imagen no disponible": "Imagen no disponible",
    "Immortal Combat": "Combate Inmortal",
    "Importancia del partido": "Importancia del partido",
    "importancia del torneo o enfrentamiento:": "importancia del torneo o enfrentamiento:",
    "Inactivo": "Inactivo",
    "Información": "Información",
    "Información general": "Información general",
    "iXCross": "iXCross",
    "iXLCross": "iXLCross",
    "JOAR": "JOAR",
    "Juanjo": "Juanjo",
    "Juanjoxd": "Juanjoxd",
    "Jugador": "Jugador",
    "Jugador Sorpresa": "Jugador revelación",
    "Julio": "Julio",
    "Juliocr36D": "Juliocr36D",
    "Kills:": "Bajas:",
    "Knockout": "Noqueo",
    "L. Puppies Represent · Titulares": "L. Puppies Represent · Titulares",
    "La Clasificación ZC26 se determina utilizando el Modelo Elo. Este método suma o resta puntos por partidos al total de puntos existente de un equipo. Los puntos que se suman o restan vienen determinados en parte por:": "La Clasificación ZC26 se determina utilizando el Modelo Elo. Este método suma o resta puntos por partidos al total de puntos existente de un equipo. Los puntos que se suman o restan vienen determinados en parte por:",
    "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competencia intensa donde solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.": "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competición intensa en la que tan solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.",
    "La FIFA adaptó este formato bajo el nombre de algoritmo \"SUMA\", el cual adaptamos directamente para los formatos 1v1 (Duels / Duelos) y 3v3 (Atrapagemas, Balón Brawl, Zona Restringida, Caza de Gemas, etc.):": "La FIFA adaptó este formato bajo el nombre de algoritmo \"SUMA\", el cual adaptamos directamente para los formatos 1v1 (Duels / Duelos) y 3v3 (Atrapagemas, Balón Brawl, Zona Restringida, Caza de Gemas, etc.):",
    "La fórmula base": "La fórmula base",
    "La fórmula base del algoritmo SUMA es:": "La fórmula base del algoritmo SUMA es:",
    "La hazaña de RobertBV: 100% de victorias sin perder una sola ronda": "La hazaña de RobertBV: 100% de victorias sin perder una sola ronda",
    "La ZC26 vuelve este septiembre": "La ZC26 vuelve este septiembre",
    "Leaderboard": "Leaderboard",
    "leafy bushes": "Arbustos Frondosos",
    "LEV": "LEV",
    "LEV WINNER": "VICTORIA DE LEV",
    "LEVIATÁN ESPORT · Titulares": "LEVIATÁN ESPORT · Titulares",
    "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 Agosto": "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 de agosto",
    "LEVIATÁN ESPORTS toma el primer puesto tras coronarse campeón de la ZC26 Agosto": "LEVIATÁN ESPORTS toma el primer puesto tras coronarse campeón de la ZC26 Agosto",
    "Lo más destacado del ranking": "Lo más destacado de la clasificación",
    "Logros": "Logros",
    "Los invitamos a ponerse de acuerdo con sus compañeros, armar sus alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que manténganse atentos a los anuncios.": "Os invitamos a poneros de acuerdo con vuestros compañeros, montar vuestras alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que estad muy atentos aos anuncios.",
    "LPR": "LPR",
    "Lugar:": "Lugar:",
    "Marcador": "Marcador",
    "Master Combat": "Combate Maestro",
    "MATCHES, AUG 8": "PARTIDOS, 8 DE AGOSTO",
    "Mayor a menor": "De mayor a menor",
    "Mayor bajada": "Mayor bajada",
    "Mayor subida": "Mayor subida",
    "Mayor valor a las rondas de eliminación directa (Playoffs) frente a las fases de grupos o clasificatorias abiertas.": "Mayor valor a las rondas de eliminación directa (Playoffs) frente a las fases de grupos o clasificatorias abiertas.",
    "Mejor Clasificación": "Mejor clasificación",
    "Mejor contribución": "Mejor contribución",
    "Mejor jugada": "Mejor jugada",
    "MEJOR JUGADA": "MEJOR JUGADA",
    "Menor a mayor": "De menor a mayor",
    "Menor impacto en partidas de exhibición o scrims oficiales; mayor impacto en fases finales de torneos Mayor/Championship.": "Menor impacto en partidas de exhibición o scrims oficiales; mayor impacto en fases finales de torneos Mayor/Championship.",
    "Modalidad: 3 vs 3 · Bo5 · Tier S": "Modalidad: 3 vs 3 · Md5 · Nivel S",
    "Momentos de la BSC de la ZC26™": "Momentos de la BSC de la ZC26™",
    "Mostrar Clasificación completa": "Mostrar clasificación completa",
    "Mostrar menos": "Mostrar menos",
    "Mostrar más": "Mostrar más",
    "mostrar más": "mostrar más",
    "Movimiento": "Movimiento",
    "MVP:": "Mejor Jugador (MVP):",
    "Más info.": "Más información",
    "Más información sobre": "Más información sobre",
    "Más información sobre cómo se calcula la Clasificación": "Más información sobre cómo se calcula la Clasificación",
    "Más partidos": "Más partidos",
    "MÁS ZC26": "MÁS ZC26",
    "N/A": "N/D",
    "NA": "NA",
    "Nacaru": "Nacaru",
    "Nacimiento": "Nacimiento",
    "Nacionalidad": "Nacionalidad",
    "Nada": "Nada",
    "NEW": "NUEVO",
    "Ninja": "Ninja",
    "Nivel general de juego mostrado en competencia, según su balance de victorias en sets y mapas.": "Nivel general de juego mostrado en competición, según su balance de victorias en sets y mapas.",
    "Nivel relativo del jugador": "Nivel relativo del jugador",
    "No hace falta ser un experto en competencias para sumarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.": "No hace falta ser un experto en competiciones para apuntarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.",
    "No hay logros registrados": "No hay logros registrados",
    "No hay partidas con ese filtro": "No hay partidas con ese filtro",
    "No se encontró ningún jugador con estos filtros.": "No se ha encontrado ningún jugador con estos filtros.",
    "No se encontró ningún jugador.": "No se ha encontrado ningún jugador.",
    "No se pudo cargar el archivo de idioma:": "No se ha podido cargar el archivo de idioma:",
    "Novedades de la Clasificación": "Novedades de la Clasificación",
    "Nueva clasificación más alta": "Nueva clasificación más alta",
    "Nuevo": "Nuevo",
    "Ocultar Clasificación completa": "Ocultar clasificación completa",
    "Orden": "Orden",
    "Organización del Evento: ZC26 BSC (Brawl Stars Championship)": "Organización del evento: ZC26 BSC (Campeonato de Brawl Stars)",
    "Otras novedades": "Otras novedades",
    "Otro punto en el que pusimos mucho esfuerzo fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.": "Otro aspecto en el que pusimos mucho empeño fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.",
    "P = P_antes + I × (W − We)": "P = P_antes + I × (W − We)",
    "P_antes:": "P_antes:",
    "P_inicial = 1600 − (R − 1) × 4": "P_inicial = 1600 − (R − 1) × 4",
    "Para esta edición decidimos renovar varias cosas. Incorporamos nuevas reglas y mecánicas de juego que buscan equilibrar la cancha para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.": "Para esta edición hemos decidido renovar varias cosas. Hemos incorporado nuevas reglas y mecánicas de juego que buscan equilibrar el terreno para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.",
    "Para iniciar una nueva temporada competitiva, los equipos y jugadores se posicionan de forma homogénea en una escala de 800 a 1600 puntos según sus resultados del año anterior. La diferencia base entre cada puesto del ranking es de 4 puntos.": "Para iniciar una nueva temporada competitiva, los equipos y jugadores se posicionan de forma homogénea en una escala de 800 a 1600 puntos según sus resultados del año anterior. La diferencia base entre cada puesto del ranking es de 4 puntos.",
    "Partidas (PG-PP):": "Partidas (V-D):",
    "Partidas recientes": "Partidas recientes",
    "Partners": "Colaboradores",
    "PARTNERS": "COLABORADORES",
    "PayPal": "PayPal",
    "País": "País",
    "Peor clasificación": "Peor clasificación",
    "PG-PP": "V-D",
    "Player Tag / Player ID": "Etiqueta de jugador / ID de jugador",
    "Por confirmar": "Por confirmar",
    "Porcentaje de victorias": "Tasa de victorias",
    "Posiciones": "Clasificaciones",
    "Posición en el ranking": "Posición en la clasificación",
    "Posición promedio": "Posición media",
    "Potencial": "Potencial",
    "Premia el rendimiento constante: elimina el estancamiento de puntos y permite que las sorpresas (upsets) de equipos emergentes en modos 1v1 o 3v3 se reflejen de inmediato en la tabla general.": "Premia el rendimiento constante: elimina el estancamiento de puntos y permite que las sorpresas (upsets) de equipos emergentes en modos 1v1 o 3v3 se reflejen de inmediato en la tabla general.",
    "PREMIOS": "PREMIOS",
    "Proceso de conversión inicial (Seeding de Temporada)": "Proceso de conversión inicial (Seeding de Temporada)",
    "Promedio de puntos por torneo": "Media de puntos por torneo",
    "Promedio DPS de Equipo": "Promedio de daño por segundo del equipo",
    "Protección en Knockout de Finals: los equipos eliminados en los Brackets de Eliminación Directa de un torneo presencial o Major no pierden puntos de ranking, incluso frente a un rival de menor puntaje (si W − We es menor que 0, entonces P = P_antes). Esto protege el esfuerzo de los equipos por haber clasificado a las etapas finales presenciales.": "Protección en Knockout de Finals: los equipos eliminados en los Brackets de Eliminación Directa de un torneo presencial o Major no pierden puntos de ranking, incluso frente a un rival de menor puntaje (si W − We es menor que 0, entonces P = P_antes). Esto protege el esfuerzo de los equipos por haber clasificado a las etapas finales presenciales.",
    "Próxima actualización oficial: 25 septiembre 2026": "Próxima actualización oficial: 25 de septiembre de 2026",
    "pts": "pts",
    "puedes obtener beneficios dentro de la comunidad.": "puedes obtener ventajas dentro de la comunidad.",
    "Punto de campeonato": "Punto de campeonato",
    "PUNTO DE CAMPEONATO": "PUNTO DE CAMPEONATO",
    "puntos del jugador o equipo antes del set/partida.": "puntos del jugador o equipo antes del set/partida.",
    "Puntos totales:": "Puntos totales:",
    "Qué tan alto puede llegar el jugador, según sus puntos acumulados frente al máximo del ranking.": "Qué tan alto puede llegar el jugador, según sus puntos acumulados frente al máximo de la clasificación.",
    "Qué tan reconocido y famoso es el jugador a nivel internacional, más allá de su liga local.": "Qué tan reconocido y famoso es el jugador a nivel internacional, más allá de su liga local.",
    "Rango Mítico": "Rango Mítico",
    "Ranking": "Clasificación",
    "RANKING": "CLASIFICACIÓN",
    "Ranking 1vs1": "Ranking 1vs1",
    "Ranking 3vs3": "Ranking 3vs3",
    "Ranking General": "Ranking General",
    "Reconocimientos especiales": "Reconocimientos especiales",
    "Redes oficiales:": "Redes oficiales:",
    "Redes sociales": "Redes sociales",
    "Región": "Región",
    "Reglas especiales para el competitivo de Brawl Stars": "Reglas especiales para el competitivo de Brawl Stars",
    "Regresa la ZC26 Brawl Stars este mes de septiembre": "La ZC26 de Brawl Stars vuelve este mes de septiembre",
    "Regresar": "Volver",
    "Reputación Int.": "Reputación Int.",
    "Reputación Internacional": "Reputación Internacional",
    "Restablecer filtros": "Restablecer filtros",
    "Resultado del partido": "Resultado del partido",
    "resultado del set/partida — 1 = victoria clara (ej. 2-0 o 3-0 en sets); 0.5 = empate/desempate por objetivos; 0 = derrota.": "resultado del set/partida — 1 = victoria clara (ej. 2-0 o 3-0 en sets); 0.5 = empate/desempate por objetivos; 0 = derrota.",
    "Resultado esperado del partido": "Resultado esperado del partido",
    "resultado esperado según la diferencia de nivel, calculado como:": "resultado esperado según la diferencia de nivel, calculado como:",
    "Resultado: el Equipo A suma 17 puntos (P = 1317) y el Equipo B pierde 17 puntos (P = 1483).": "Resultado: el Equipo A suma 17 puntos (P = 1317) y el Equipo B pierde 17 puntos (P = 1483).",
    "RESUMEN AGOSTO": "RESUMEN DE AGOSTO",
    "Rol": "Rol",
    "Ronda 1": "Ronda 1",
    "Ronda 2": "Ronda 2",
    "Rondas Ganadas (Sets)": "Rondas ganadas (Sets)",
    "Rondas:": "Rondas:",
    "Récord de mapas/modos (PG-PP)": "Historial de mapas/modos (V-D)",
    "Récord de sets (G-P)": "Historial de sets (V-D)",
    "SA": "SA",
    "SALON DE LA FAMA": "SALÓN DE LA FAMA",
    "Salón de la fama": "Salón de la Fama",
    "Salón de la Fama": "Salón de la Fama",
    "Sanciones": "Sanciones",
    "Se actualiza con cada contribucion a ZC26": "Se actualiza con cada contribución a la ZC26",
    "Se actualiza con cada torneo de ZC26": "Se actualiza con cada torneo de la ZC26",
    "Según los datos de los partidos": "Según los datos de las partidas",
    "Seleccion completa": "Selección completa",
    "Semana de movimientos: varios equipos entran al Top 10 de la Clasificación": "Semana de movimientos: varios equipos entran al Top 10 de la Clasificación",
    "Sembrado #100: P_inicial = 1204": "Sembrado #100: P_inicial = 1204",
    "Sembrado #200: P_inicial = 804": "Sembrado #200: P_inicial = 804",
    "Sembrado #3: P_inicial = 1592": "Sembrado #3: P_inicial = 1592",
    "Semifinal": "Semifinal",
    "Servidores Globales, Brawl Stars": "Servidores globales, Brawl Stars",
    "Set Marcado:": "Set anotado:",
    "Sets": "Sets",
    "Sets (G-P):": "Sets (V-D):",
    "Sets ajustados (Bracket de Perdedores / Tiebreaker): un set decidido en la última partida decisiva (ej. 2-1 en sets o en tiempo suplementario de Balón Brawl) otorga un valor de victoria parcial para el ganador y no penaliza severamente al perdedor. Si el set se decide en Tiebreaker estricto: W del equipo ganador = 0.75, W del equipo perdedor = 0.5.": "Sets ajustados (Bracket de Perdedores / Tiebreaker): un set decidido en la última partida decisiva (ej. 2-1 en sets o en tiempo suplementario de Balón Brawl) otorga un valor de victoria parcial para el ganador y no penaliza severamente al perdedor. Si el set se decide en Tiebreaker estricto: W del equipo ganador = 0.75, W del equipo perdedor = 0.5.",
    "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como corrección de nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor contáctanos a través de los medios oficiales indicados arriba.": "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como la corrección del nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor, ponte en contacto con nosotros a través de los medios oficiales indicados arriba.",
    "Silenciar sonidos": "Silenciar sonidos",
    "Sin partidas registradas": "Sin partidas registradas",
    "Sobre la nueva fórmula": "Sobre la nueva fórmula",
    "Subcampeón": "Subcampeón",
    "Subcampeón · 250 pts": "Subcampeón · 250 pts",
    "Subcampeón · 250 pts · +25 Estelar (Set 2)": "Subcampeón · 250 pts · +25 Estelar (Set 2)",
    "Subida": "Ascenso",
    "Suplente · LEV": "Suplente · LEV",
    "Suplentes": "Suplentes",
    "Sí": "Sí",
    "TA:": "TA:",
    "Taikisha, elegido MVP de la Gran Final": "Taikisha, elegido Mejor Jugador de la Gran Final",
    "TAIKISHA, MVP": "TAIKISHA, MVP",
    "Taikisha, MVP 🏆": "Taikisha, Mejor Jugador 🏆",
    "También podría interesarle...": "También podría interesarle...",
    "Tarjetas Amarillas": "Tarjetas amarillas",
    "Tarjetas Rojas": "Tarjetas rojas",
    "Tier": "Tier",
    "Tier-A": "Tier-A",
    "Tier-B": "Tier-B",
    "Tier-S": "Tier-S",
    "TikTok": "TikTok",
    "tire maniacs": "Locura de Neumáticos",
    "Titular": "Titular",
    "Titular · Capitán": "Titular · Capitán",
    "Todas las novedades de la Clasificación": "Todas las novedades de la Clasificación",
    "Todo el contenido publicado en esta página se ofrece de forma gratuita e informativa. No está permitido redistribuir, copiar ni reutilizar el contenido original sin autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.": "Todo el contenido publicado en esta página se ofrece de forma gratuita y con carácter informativo. No está permitido redistribuir, copiar ni reutilizar el contenido original sin la autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.",
    "Todos": "Todos",
    "Todos los horarios corresponden a la hora estándar de Sudamérica": "Todos los horarios corresponden a la hora estándar de Sudamérica",
    "Todos los horarios corresponden a la hora estándar regional": "Todos los horarios corresponden a la hora estándar regional",
    "Todos los partidos": "Todos los partidos",
    "Top 1 Global (Sembrado #1): P_inicial = 1600": "Top 1 Global (Sembrado #1): P_inicial = 1600",
    "Torneo": "Torneo",
    "Torneo virtual \"ZC26 AUGT8\", manejado por el equipo del soporte": "Torneo virtual \"ZC26 AUGT8\", gestionado por el equipo de soporte",
    "TR:": "TR:",
    "Términos de uso": "Términos de uso",
    "Títulos:": "Títulos:",
    "Ver completo": "Ver al completo",
    "Ver estadisticas": "Ver estadísticas",
    "Ver todos los partidos": "Ver todos los partidos",
    "Versión 2.0.9.6": "Versión 2.0.9.6",
    "Versión 4.2.0.19": "Versión 4.2.0.19",
    "Victorias": "Victorias",
    "Volver arriba": "Volver arriba",
    "W:": "W:",
    "Watch Game": "Ver partido",
    "We = 1 / (10^(−dr/600) + 1)": "We = 1 / (10^(−dr/600) + 1)",
    "We:": "We:",
    "WIN LEVIATAN ESPORT": "VICTORIA DE LEVIATAN ESPORT",
    "winner": "ganador",
    "YouTube": "YouTube",
    "Z. Jack": "Z. Jack",
    "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)": "ZC ESPORTS · ZC26 · BSC (Campeonato de Brawl Stars)",
    "ZC26 - Brawl Stars Championship": "ZC26 - Campeonato de Brawl Stars",
    "ZC26 1v1 Edición 4 · 3er y 4to Lugar": "ZC26 1v1 Edición 4 · 3er y 4º puesto",
    "ZC26 1v1 Edición 4 · Gran Final": "ZC26 1v1 Edición 4 · Gran Final",
    "ZC26 1v1 Edición 4 · Ronda 1": "ZC26 1v1 Edición 4 · Ronda 1",
    "ZC26 1v1 Edición 4 · Ronda 2": "ZC26 1v1 Edición 4 · Ronda 2",
    "ZC26 1v1 Edición 4 · Semifinal": "ZC26 1v1 Edición 4 · Semifinal",
    "ZC26 1v1 · 3er y 4to Lugar": "ZC26 1v1 · 3er y 4º puesto",
    "ZC26 1v1 · Gran Final": "ZC26 1v1 · Gran Final",
    "ZC26 1v1 · Ronda 1": "ZC26 1v1 · Ronda 1",
    "ZC26 1v1 · Ronda 2": "ZC26 1v1 · Ronda 2",
    "ZC26 1v1 · Semifinal": "ZC26 1v1 · Semifinal",
    "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.": "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.",
    "ZC26 ESPORTS™": "ZC26 ESPORTS™",
    "ZC26 GRAN FINAL": "ZC26 GRAN FINAL",
    "ZC26 · 3er y 4to Lugar": "ZC26 · 3er y 4º puesto",
    "ZC26 · Gran Final": "ZC26 · Gran Final",
    "ZC26 · Semifinal": "ZC26 · Semifinal",
    "zc26.esports.official@gmail.com": "zc26.esports.official@gmail.com",
    "Zona horaria:": "Zona horaria:",
    "Zyroxs escala 18 puestos tras coronarse campeón del Torneo Duelos ZC26": "Zyroxs escala 18 puestos tras coronarse campeón del Torneo Duelos ZC26",
    "© ZC26 | Todos los derechos reservados.": "© ZC26 | Todos los derechos reservados.",
    "·": "·",
    "¿Cómo se calcula la Clasificación?": "¿Cómo se calcula la Clasificación?",
    "¿Quieres apoyar a ZC26? Con una donación desde 1 dólar a través de": "¿Quieres apoyar a ZC26? Con una donación a partir de 1 dólar a través de",
    "Álvaro": "Álvaro",
    "Última actualización: 30 agosto, 2026": "Última actualización: 30 de agosto de 2026",
    "Última actualización: 6 dic, 2025": "Última actualización: 6 de dic. de 2025",
    "Última actualización: viernes, 11 de Septiembre de 2026, 14:54": "Última actualización: viernes, 11 de septiembre de 2026, 14:54",
    "Última Clasificación": "Última clasificación",
    "Último partido importa": "El último partido importa",
    "ÚLTIMO PARTIDO IMPORTA": "EL ÚLTIMO PARTIDO IMPORTA",
    "–": "-",
    "✕": "✕"
};
