// idioma/pt.js
// Diccionario Português. Clave = texto original en español (LatAm), Valor = traducción.
// Coincidencia EXACTA (recortando espacios). Cubre: interfaz completa, novedades,
// filtros/footer, etiquetas de tarjetas de jugador y combinaciones de torneo/resultado.

var ZC_LANG_PT = {
    "% de Victoria": "% de Vitória",
    "0": "0",
    "0-2": "0-2",
    "0.0": "0,0",
    "0/11": "0/11",
    "08/09/26": "08/09/26",
    "1": "1",
    "1-2": "1-2",
    "104.0": "104,0",
    "11 Rondas": "11 Rodadas",
    "11/11": "11/11",
    "118.4": "118,4",
    "129.9": "129,9",
    "132.5": "132,5",
    "15": "15",
    "153.1": "153,1",
    "17', 26'": "17', 26'",
    "19": "19",
    "1er Lugar": "1º Lugar",
    "1er lugar · 120 pts": "1º lugar · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 0 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 0 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 2 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 2 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 4 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 4 · 120 pts",
    "1st": "1º",
    "1st Champion": "1º Campeão",
    "2": "2",
    "2-1": "2-1",
    "20": "20",
    "20'": "20'",
    "25%": "25%",
    "26": "26",
    "27": "27",
    "2do Lugar": "2º Lugar",
    "2do lugar · 80 pts": "2º lugar · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 6 - 4 · 80 pts": "2º lugar · Sets 3 - 1 · V-D 6 - 4 · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 8 - 4 · 80 pts": "2º lugar · Sets 3 - 1 · V-D 8 - 4 · 80 pts",
    "2nd": "2º",
    "2nd Runner-Up": "Terceiro lugar",
    "3": "3",
    "34": "34",
    "34'": "34'",
    "3er Lugar": "3º Lugar",
    "3er lugar · 105 pts": "3º lugar · 105 pts",
    "3er lugar · 50 pts": "3º lugar · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 6 - 2 · 50 pts": "3º lugar · Sets 3 - 1 · V-D 6 - 2 · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 7 - 2 · 50 pts": "3º lugar · Sets 3 - 1 · V-D 7 - 2 · 50 pts",
    "3er lugar · Sets 3 - 2 · PG-PP 7 - 6 · 50 pts": "3º lugar · Sets 3 - 2 · V-D 7 - 6 · 50 pts",
    "3er y 4to Lugar": "3º e 4º Lugar",
    "3er-4to Lugar": "3º-4º Lugar",
    "3rd-4th Place": "3º e 4º Lugar",
    "3rd-4th place": "3º-4º lugar",
    "4to Lugar": "4º Lugar",
    "4to lugar · 100 pts": "4º lugar · 100 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 4 - 4 · 45 pts": "4º lugar · Sets 2 - 2 · V-D 4 - 4 · 45 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 5 - 4 · 45 pts": "4º lugar · Sets 2 - 2 · V-D 5 - 4 · 45 pts",
    "5.8": "5,8",
    "6.0": "6,0",
    "60": "60",
    "7.1": "7,1",
    "7.6": "7,6",
    "75%": "75%",
    "8'": "8'",
    "8.6": "8,6",
    "80.8": "80,8",
    "81": "81",
    "9": "9",
    "9.4": "9,4",
    "94.8": "94,8",
    "98.0": "98,0",
    "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aporte al equipo.": "A nível individual, o jogador Taikisha foi reconhecido como a figura mais destacada do evento por seu brilhante desempenho ao longo das partidas, recebendo um bônus especial por sua contribuição à equipe.",
    "Abrir menú": "Abrir menu",
    "Actividad": "Atividade",
    "Activo": "Ativo",
    "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competencia.": "Além disso, contaremos com uma equipe de moderação dedicada a revisar cada partida de perto, garantindo que o ambiente se mantenha limpo, respeitoso e ordenado durante os dias de competição.",
    "Agradecemos la participación de todos los competidores y les invitamos a mantenerse atentos a las próximas ediciones.": "Agradecemos a participação de todos os competidores e convidamos vocês a ficarem atentos às próximas edições.",
    "Al conseguir los créditos necesarios, se abrirá una pantalla especial donde se mostrarán los personajes disponibles. Al tocar la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.": "Ao conseguir os créditos necessários, uma tela especial será aberta onde os personagens disponíveis serão mostrados. Ao tocar na tela, as opções vão se eliminando uma a uma até revelar o personagem obtido.",
    "Alineaciones": "Escalações",
    "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.": "Antes do início dos confrontos na grande final, ambas as equipes aplicaram sua estratégia na fase de vetos. Ficaram excluídos da partida os personagens Belle, Spike, Bibi e Nori, o que obrigou as equipes a reformularem suas composições táticas para a série decisiva.",
    "Apoyamos y síguenos en nuestras redes sociales": "Apoie-nos e siga-nos nas nossas redes sociais",
    "ASIA": "ÁSIA",
    "Argentina": "Argentina",
    "As de Combate": "Ás de Combate",
    "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatorio.": "Da mesma forma, no dia vinte e nove de agosto serão entregues mil e quinhentos créditos como compensação pelos ajustes no sistema. Os jogadores poderão decidir se usam esses créditos antes da atualização para conseguir o personagem que estão desbloqueando atualmente ou guardá-los para o novo sistema aleatório.",
    "Asist.:": "Assist.:",
    "Asistencias": "Assistências",
    "Así se jugó la final: Leviatán se impuso 3-1 en los mapas": "Assim foi jogada a final: Leviatán venceu por 3-1 nos mapas",
    "Ataques": "Ataques",
    "Aug 8, 26": "8 de ago., 26",
    "Aún no hay estadísticas de defensa registradas para este partido.": "Ainda não há estatísticas de defesa registradas para esta partida.",
    "Balance de mapas o modos ganados y perdidos.": "Saldo de mapas ou modos vencidos e perdidos.",
    "Balance de sets ganados y perdidos en la competencia.": "Saldo de sets vencidos e perdidos na competição.",
    "Baneos globales": "Banimentos globais",
    "Belle rock": "Rocha da Belle",
    "Bolivia": "Bolívia",
    "Brasil": "Brasil",
    "Capacidad para controlar el mapa y mantener buena posición durante la partida.": "Capacidade de controlar o mapa e manter um bom posicionamento durante a partida.",
    "Capacidad para sobrevivir y reducir el daño recibido en combate.": "Capacidade de sobreviver e reduzir o dano recebido em combate.",
    "Chile": "Chile",
    "Colombia": "Colômbia",
    "Contribución en la captura o cumplimiento de los objetivos del modo.": "Contribuição na captura ou cumprimento dos objetivos do modo.",
    "Control de Zona y Posicionamiento": "Controle de Zona e Posicionamento",
    "EMEA (Europa, Medio Oriente y África)": "EMEA (Europa, Oriente Médio e África)",
    "Ecuador": "Equador",
    "Eficiencia en Combate (K/D/A)": "Eficiência em Combate (K/D/A)",
    "El Salvador": "El Salvador",
    "España": "Espanha",
    "Ghana": "Gana",
    "Gran Maestro de Combate": "Grande Mestre de Combate",
    "Guatemala": "Guatemala",
    "Habilidades": "Habilidades",
    "Honduras": "Honduras",
    "Impacto y Uso del Súper": "Impacto e Uso do Super",
    "K/D/A": "K/D/A",
    "L. Puppies Represent": "L. Puppies Represent",
    "LEVIATÁN ESPORTS se coronó campeón de la Gran Final ZC26 el 09/08/26 tras vencer 3-1 a Cachorritas repres (LPR). Título obtenido con la alineación de Julio (capitán), iXLCross y JOAR.": "A LEVIATÁN ESPORTS se sagrou campeã da Grande Final da ZC26 em 09/08/26 após vencer a Cachorritas repres (LPR) por 3-1. O título foi conquistado com a escalação de Julio (capitão), iXLCross e JOAR.",
    "Leviatán Esports": "Leviatán Esports",
    "Maestro de Combate": "Mestre de Combate",
    "Mapas": "Mapas",
    "Mayor descenso": "Maior Queda",
    "Mejor clasificación": "Melhor Classificação",
    "Más puntos conseguidos": "Mais Pontos Conquistados",
    "Más puntos perdidos": "Mais Pontos Perdidos",
    "México": "México",
    "Norteamérica": "América do Norte",
    "Objetivos": "Objetivos",
    "Perú": "Peru",
    "Pool": "Pool",
    "Porcentaje de Victorias": "Porcentagem de Vitórias",
    "Porcentaje de partidas o sets ganados sobre el total jugado.": "Porcentagem de partidas ou sets vencidos sobre o total jogado.",
    "Potencial": "Potencial",
    "Promedio de Puntos por Torneo": "Média de Pontos por Torneio",
    "Pts/Torneo": "Pts/Torneio",
    "Puntos obtenidos en promedio por cada torneo disputado.": "Pontos obtidos em média por torneio disputado.",
    "Qué tan efectivo es usando su habilidad Súper en el momento correcto.": "Quão eficaz é o uso da habilidade Super no momento certo.",
    "Qué tan variado y flexible es su repertorio de personajes al draftear.": "Quão variado e flexível é o repertório de personagens ao draftar.",
    "Rango Mítico": "Rank Mítico",
    "Relación entre eliminaciones, muertes y asistencias en combate.": "Relação entre eliminações, mortes e assistências em combate.",
    "Reputación Int.": "Reputação Int.",
    "Récord de Mapas/Modos (PG-PP)": "Recorde de Mapas/Modos (V-D)",
    "Récord de Sets (G-P)": "Recorde de Sets (V-D)",
    "Sudamérica": "América do Sul",
    "Superviv.": "Sobreviv.",
    "Supervivencia y Mitigación de Daño": "Sobrevivência e Mitigação de Dano",
    "Súper": "Super",
    "Toma de Objetivos del Modo de Juego": "Conquista de Objetivos do Modo de Jogo",
    "Venezuela": "Venezuela",
    "Versatilidad de Pool (Drafteo)": "Versatilidade de Pool (Draft)",
    "Victorias %": "Vitórias %",
    "Zona": "Zona",
    "belle y spike": "Belle e Spike",
    "Bibi y Nori": "Bibi e Nori",
    "Brawl Ball": "Fute-Brawl",
    "Brawl Stars Oficial": "Brawl Stars Oficial",
    "Brawl Stars · Agosto 8 de 2026": "Brawl Stars · 8 de agosto de 2026",
    "BRAWLER BLAST": "EXPLOSÃO BRAWLER",
    "Brawlers principales": "Brawlers principais",
    "BSC, AUG 8": "BSC, 8 DE AGO.",
    "Buscar por nombre, ID o país...": "Pesquisar por nome, ID ou país...",
    "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, como puntos de fuerza, gadgets, habilidades estelares, engranajes o hipercargas. Siempre se asegurará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.": "Cada descarte concederá fragmentos de gemas que se converterão diretamente em melhorias para o personagem, como pontos de força, gadgets, poderes estrela, engrenagens ou hipercargas. Sempre será assegurado pelo menos um nível de força, com a possibilidade de obter um personagem melhorado ao máximo.",
    "Calificaciones de los jugadores (0/11) basadas en los datos de los partidos": "Avaliações dos jogadores (0/11) com base nos dados das partidas",
    "Calificación del jugador": "Avaliação do jogador",
    "Campeones a lo largo de los torneos ZC26": "Campeões ao longo dos torneios ZC26",
    "Campeón": "Campeão",
    "Campeón · 500 pts · +25 Estelar (Set 1)": "Campeão · 500 pts · +25 Estelar (Set 1)",
    "Campeón · 500 pts · +25 Estelar (Set 3)": "Campeão · 500 pts · +25 Estelar (Set 3)",
    "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP": "Campeão · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP",
    "Campeón · Suplente (no disputó rondas)": "Campeão · Suplente (não disputou rodadas)",
    "Champion": "Campeão",
    "Clasificación actual": "Classificação atual",
    "Clasificatoria": "Ranqueada",
    "Coach": "Treinador",
    "COMENTARIOS": "COMENTÁRIOS",
    "Con estos resultados, la tabla general de posiciones quedó encabezada por Leviatán Esports en el primer lugar, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.": "Com esses resultados, a tabela geral de posições ficou encabeçada pela Leviatán Esports em primeiro lugar, escoltada pelo vice-campeão na segunda posição e fechando o pódio com o terceiro lugar do torneio.",
    "Contacto": "Contato",
    "Contacto comercial y soporte:": "Contato comercial e suporte:",
    "Contribucion": "Contribuição",
    "Contribución total": "Contribuição total",
    "Copyrights © ZC ESPORTS 2026": "Direitos autorais © ZC ESPORTS 2026",
    "CREDITOS": "CRÉDITOS",
    "Cronología": "Cronologia",
    "Créditos aprox.": "Créditos aprox.",
    "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.": "Quando um novo personagem for adicionado ao jogo, este se somará à lista de sua respectiva raridade e poderá aparecer no Brawler Blast, embora não se possa priorizar seu desbloqueio imediato.",
    "Datos de Brawl Stars": "Dados de Brawl Stars",
    "Datos destacados": "Dados em destaque",
    "Defensas": "Defesas",
    "Descenso": "Queda",
    "Después de ese evento, nos tomamos un tiempo fuera de las canchas para planificar todo con calma, pero la espera terminó y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta oportunidad, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.": "Depois desse evento, tiramos um tempo fora das quadras para planejar tudo com calma, mas a espera acabou e estamos de volta oficialmente com uma nova edição da ZC26. Desta vez, voltaremos a medir o nível de todos na modalidade de três contra três dentro do Brawl Stars.",
    "Discord": "Discord",
    "doble swoosh": "Duplo Swoosh",
    "DPS:": "DPS:",
    "Edición 4": "Edição 4",
    "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se jugó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.": "O desenvolvimento do encontro final mostrou um desempenho firme por parte da Leviatán Esports, superando seu rival por um placar de três sets a um. O primeiro set foi jogado no mapa Pneus Pirados, onde a Leviatán assumiu a vantagem inicial com uma vitória limpa de dois a zero.",
    "El encuentro terminó.": "A partida terminou.",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast": "O sistema Trilha Estelar será substituído por uma nova mecânica chamada Explosão Brawler",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de manera aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.": "O sistema Caminho Starr será substituído por uma nova mecânica chamada Brawler Blast. Com esta mudança, ao reunir a quantidade de créditos necessária, um personagem será desbloqueado de maneira aleatória dentro de uma determinada raridade, concedendo além disso progressão extra para o referido personagem.",
    "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su final, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competencia estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.": "O torneio oficial de três contra três do Brawl Stars chegou ao fim, consagrando a Leviatán Esports como a grande campeã desta edição inaugural. A jornada de competição foi marcada por um nível técnico sobressalente e séries de alta intensidade em cada uma das rodadas disputadas.",
    "Eliminaciones (Kills)": "Eliminações (Abates)",
    "EMEA": "EMEA",
    "En el segundo mapa, Roca de Belle, el conjunto rival logró responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un categórico dos a cero.": "No segundo mapa, Rocha da Belle, o conjunto rival conseguiu responder e empatar a série ao conquistar o ponto com um resultado de dois a um. No entanto, a Leviatán recuperou o controle das ações no terceiro mapa, Arbustos Densos, impondo-se dois a um em um duelo muito disputado, e finalmente fechou o campeonato no mapa Giro Duplo com um categórico dois a zero.",
    "Equipo": "Equipe",
    "Equipo de Apoyo": "Equipe de Apoio",
    "Estado": "Status",
    "Escalafón": "Escada",
    "Estadísticas": "Estatísticas",
    "Estadísticas clave": "Estatísticas principais",
    "Estadísticas del partido": "Estatísticas da partida",
    "Estadísticas generales del partido": "Estatísticas gerais da partida",
    "Estadísticas y rendimiento competitivo": "Estatísticas e desempenho competitivo",
    "Estimada comunidad, nos alegra mucho ponernos en contacto con ustedes para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordarán, en la última edición el equipo de Levantan Esports se quedó con el primer lugar tras una excelente participación.": "Estimada comunidade, estamos muito felizes em entrar em contato com vocês para compartilhar várias novidades importantes sobre o desenvolvimento dos nossos torneios. Como bem devem se lembrar, na última edição a equipe da Levantan Esports ficou com o primeiro lugar após uma excelente participação.",
    "Eventos:": "Eventos:",
    "Faltas": "Faltas",
    "Filtro": "Filtro",
    "Filtros": "Filtros",
    "Fin": "Fim",
    "Finalized": "Finalizado",
    "Finished": "Encerrado",
    "Ganancias aprox.": "Ganhos aprox.",
    "Gem Grab": "Pique-Gema",
    "Gmail": "Gmail",
    "GRAN FINAL": "GRANDE FINAL",
    "Gran Final": "Grande Final",
    "Gran Final 🏆": "Grande Final 🏆",
    "Heist": "Roubo",
    "Highlights": "Melhores momentos",
    "Historias destacadas": "Histórias de destaque",
    "Home": "Início",
    "HOME": "INÍCIO",
    "IDs alternos": "IDs alternativos",
    "Imagen no disponible": "Imagem não disponível",
    "Inactivo": "Inativo",
    "Información": "Informação",
    "Información del jugador": "Informações do jogador",
    "Información general": "Informações gerais",
    "iXCross": "iXCross",
    "iXLCross": "iXLCross",
    "JOAR": "JOAR",
    "Juanjo": "Juanjo",
    "Juanjoxd": "Juanjoxd",
    "Jugador": "Jogador",
    "Jugador Sorpresa": "Jogador Surpresa",
    "Julio": "Julio",
    "Juliocr36D": "Juliocr36D",
    "Kills:": "Abates:",
    "Knockout": "Nocaute",
    "L. Puppies Represent · Titulares": "L. Puppies Represent · Titulares",
    "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competencia intensa donde solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.": "A estrutura do torneio foi pensada para manter a emoção do início ao fim, pois será uma competição intensa onde apenas uma equipe conseguirá levar o troféu de campeã. Sabemos que a exigência é alta, por isso esperamos ver partidas muito disputadas entre os melhores grupos que se apresentarem.",
    "La ZC26 vuelve este septiembre": "O ZC26 retorna neste mês de setembro",
    "leafy bushes": "Arbustos Frondosos",
    "LEV": "LEV",
    "LEV WINNER": "VITÓRIA DA LEV",
    "LEVIATÁN ESPORT · Titulares": "LEVIATÁN ESPORT · Titulares",
    "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 Agosto": "LEVIATÁN ESPORTS sagra-se CAMPEÃ do ZC26 de Agosto",
    "Lo más destacado del ranking": "Destaques da classificação",
    "Logros": "Conquistas",
    "Los invitamos a ponerse de acuerdo con sus compañeros, armar sus alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que manténganse atentos a los anuncios.": "Convidamos vocês a entrarem em acordo com seus companheiros, montarem suas escalações com antecedência e começarem a praticar. Nos próximos dias continuaremos publicando mais detalhes sobre os horários e a forma de registro, portanto fiquem atentos aos anúncios.",
    "LPR": "LPR",
    "Lugar:": "Local:",
    "MATCHES, AUG 8": "PARTIDAS, 8 DE AGO.",
    "Mayor a menor": "Maior para menor",
    "Mayor bajada": "Maior queda",
    "Mayor subida": "Maior subida",
    "Mejor Clasificación": "Melhor Classificação",
    "Mejor contribución": "Melhor contribuição",
    "Mejor jugada": "Melhor jogada",
    "MEJOR JUGADA": "MELHOR JOGADA",
    "Menor a mayor": "Menor para maior",
    "Modalidad: 3 vs 3 · Bo5 · Tier S": "Modalidade: 3 vs 3 · Bo5 · Tier S",
    "Momentos de la BSC de la ZC26™": "Momentos da BSC da ZC26™",
    "Mostrar Clasificación completa": "Mostrar classificação completa",
    "Mostrar menos": "Mostrar menos",
    "Mostrar más": "Mostrar mais",
    "mostrar más": "mostrar mais",
    "Movimiento": "Movimento",
    "MVP:": "MVP:",
    "Más info.": "Mais informações",
    "Más información sobre": "Mais informações sobre",
    "Más partidos": "Mais partidas",
    "MÁS ZC26": "MAIS ZC26",
    "N/A": "N/D",
    "NA": "NA",
    "Nacaru": "Nacaru",
    "Nacimiento": "Nascimento",
    "Nacionalidad": "Nacionalidade",
    "Nada": "Nada",
    "NEW": "NOVO",
    "Ninja": "Ninja",
    "No hace falta ser un experto en competencias para sumarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.": "Não é preciso ser um especialista em competições para participar; os guias e as instruções estão redigidos de forma simples para que todos saibam exatamente como se inscrever, como relatar seus resultados e como avançar em cada fase.",
    "No hay logros registrados": "Sem conquistas registradas",
    "No se encontró ningún jugador con estos filtros.": "Nenhum jogador encontrado com estes filtros.",
    "No se encontró ningún jugador.": "Nenhum jogador foi encontrado.",
    "No se pudo cargar el archivo de idioma:": "Não foi possível carregar o arquivo de idioma:",
    "Nueva clasificación más alta": "Nova classificação mais alta",
    "Nuevo": "Novo",
    "Ocultar Clasificación completa": "Ocultar Classificação completa",
    "Orden": "Ordem",
    "Organización del Evento: ZC26 BSC (Brawl Stars Championship)": "Organização do Evento: ZC26 BSC (Campeonato de Brawl Stars)",
    "Otro punto en el que pusimos mucho esfuerzo fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.": "Outro ponto no qual colocamos muito esforço foi na clareza do regulamento. Queremos que qualquer pessoa que tenha vontade de jogar possa entender o formato sem complicações, mesmo se for a primeira vez que participa de um torneio desse tipo.",
    "Para esta edición decidimos renovar varias cosas. Incorporamos nuevas reglas y mecánicas de juego que buscan equilibrar la cancha para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.": "Para esta edição decidimos renovar várias coisas. Incorporamos novas regras e mecânicas de jogo que buscam equilibrar o campo para todos os participantes. A principal ideia é que cada equipe compita em igualdade de condições, sem vantagens injustas para ninguém.",
    "Partidas (PG-PP):": "Partidas (V-D):",
    "Partidas recientes": "Partidas recentes",
    "Partners": "Parceiros",
    "PARTNERS": "PARCEIROS",
    "PayPal": "PayPal",
    "País": "País",
    "Peor clasificación": "Pior classificação",
    "PG-PP": "V-D",
    "Player Tag / Player ID": "Player Tag / Player ID",
    "Por confirmar": "A confirmar",
    "Porcentaje de victorias": "Porcentagem de vitórias",
    "Posiciones": "Tabela",
    "Posición en el ranking": "Posição no ranking",
    "Posición promedio": "Posição média",
    "PREMIOS": "PRÊMIOS",
    "Promedio de puntos por torneo": "Média de pontos por torneio",
    "Promedio DPS de Equipo": "Média de DPS da Equipe",
    "pts": "pts",
    "puedes obtener beneficios dentro de la comunidad.": "você pode obter benefícios dentro da comunidade.",
    "Punto de campeonato": "Ponto de campeonato",
    "PUNTO DE CAMPEONATO": "PONTO DE CAMPEONATO",
    "Puntos totales:": "Pontos totais:",
    "Ranking": "Classificação",
    "RANKING": "CLASSIFICAÇÃO",
    "Reconocimientos especiales": "Reconhecimentos especiais",
    "Redes oficiales:": "Redes oficiais:",
    "Redes sociales": "Redes sociais",
    "Región": "Região",
    "Regresa la ZC26 Brawl Stars este mes de septiembre": "O ZC26 de Brawl Stars retorna neste mês de setembro",
    "Regresar": "Voltar",
    "Restablecer filtros": "Redefinir filtros",
    "RESUMEN AGOSTO": "RESUMO DE AGOSTO",
    "Rol": "Função",
    "Ronda 1": "Rodada 1",
    "Ronda 2": "Rodada 2",
    "Rondas Ganadas (Sets)": "Rodadas Vencidas (Sets)",
    "Rondas:": "Rodadas:",
    "Récord de mapas/modos (PG-PP)": "Recorde de mapas/modos (V-D)",
    "Récord de sets (G-P)": "Recorde de sets (V-D)",
    "SA": "SA",
    "SALON DE LA FAMA": "HALL DA FAMA",
    "Salón de la fama": "Hall da Fama",
    "Salón de la Fama": "Hall da Fama",
    "Sanciones": "Punições",
    "Se actualiza con cada contribucion a ZC26": "É atualizado com cada contribuição para a ZC26",
    "Se actualiza con cada torneo de ZC26": "É atualizado com cada torneio da ZC26",
    "Según los datos de los partidos": "Segundo os dados das partidas",
    "Seleccion completa": "Seleção completa",
    "Semifinal": "Semifinal",
    "Servidores Globales, Brawl Stars": "Servidores Globais, Brawl Stars",
    "Set Marcado:": "Set Marcado:",
    "Sets": "Sets",
    "Sets (G-P):": "Sets (V-D):",
    "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como corrección de nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor contáctanos a través de los medios oficiales indicados arriba.": "Caso deseje solicitar alguma modificação sobre sua identidade na página — como correção de nome, região, data de nascimento, apelido, redes sociais ou outro dado associado ao seu perfil — por favor, entre em contato conosco através dos meios oficiais indicados acima.",
    "Silenciar sonidos": "Silenciar sons",
    "Sin partidas registradas": "Sem partidas registradas",
    "Subcampeón": "Vice-campeão",
    "Subcampeón · 250 pts": "Vice-campeão · 250 pts",
    "Subcampeón · 250 pts · +25 Estelar (Set 2)": "Vice-campeão · 250 pts · +25 Estelar (Set 2)",
    "Subida": "Subida",
    "Suplente · LEV": "Reserva · LEV",
    "Suplentes": "Reservas",
    "Sí": "Sim",
    "TA:": "CA:",
    "Taikisha, elegido MVP de la Gran Final": "Taikisha, eleito MVP da Grande Final",
    "TAIKISHA, MVP": "TAIKISHA, MVP",
    "Taikisha, MVP 🏆": "Taikisha, MVP 🏆",
    "Tarjetas Amarillas": "Cartões Amarelos",
    "Tarjetas Rojas": "Cartões Vermelhos",
    "TikTok": "TikTok",
    "tire maniacs": "Maníacos por Pneus",
    "Titular": "Titular",
    "Titular · Capitán": "Titular · Capitão",
    "Todo el contenido publicado en esta página se ofrece de forma gratuita e informativa. No está permitido redistribuir, copiar ni reutilizar el contenido original sin autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.": "Todo o conteúdo publicado nesta página é oferecido de forma gratuita e informativa. Não é permitido redistribuir, copiar ou reutilizar o conteúdo original sem autorização expressa da ZC26. As informações são fornecidas sem garantias e podem ser atualizadas sem aviso prévio.",
    "Todos los horarios corresponden a la hora estándar de Sudamérica": "Todos os horários correspondem à hora padrão da América do Sul",
    "Todos los horarios corresponden a la hora estándar regional": "Todos os horários correspondem à hora padrão regional",
    "Torneo virtual \"ZC26 AUGT8\", manejado por el equipo del soporte": "Torneio virtual \"ZC26 AUGT8\", gerenciado pela equipe de suporte",
    "TR:": "CV:",
    "Términos de uso": "Termos de uso",
    "Títulos:": "Títulos:",
    "Ver completo": "Ver completo",
    "Ver estadisticas": "Ver estatísticas",
    "Versión 3.0.16.5": "Versão 3.0.16.5",
    "Volver arriba": "Voltar ao topo",
    "Watch Game": "Assistir Partida",
    "WIN LEVIATAN ESPORT": "VITÓRIA DA LEVIATAN ESPORT",
    "winner": "vencedor",
    "YouTube": "YouTube",
    "Z. Jack": "Z. Jack",
    "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)": "ZC ESPORTS · ZC26 · BSC (Campeonato de Brawl Stars)",
    "ZC26 - Brawl Stars Championship": "ZC26 - Campeonato de Brawl Stars",
    "ZC26 1v1 Edición 4 · 3er y 4to Lugar": "ZC26 1v1 Edição 4 · 3º e 4º Lugar",
    "ZC26 1v1 Edición 4 · Gran Final": "ZC26 1v1 Edição 4 · Grande Final",
    "ZC26 1v1 Edición 4 · Ronda 1": "ZC26 1v1 Edição 4 · Rodada 1",
    "ZC26 1v1 Edición 4 · Ronda 2": "ZC26 1v1 Edição 4 · Rodada 2",
    "ZC26 1v1 Edición 4 · Semifinal": "ZC26 1v1 Edição 4 · Semifinal",
    "ZC26 1v1 · 3er y 4to Lugar": "ZC26 1v1 · 3º e 4º Lugar",
    "ZC26 1v1 · Gran Final": "ZC26 1v1 · Grande Final",
    "ZC26 1v1 · Ronda 1": "ZC26 1v1 · Rodada 1",
    "ZC26 1v1 · Ronda 2": "ZC26 1v1 · Rodada 2",
    "ZC26 1v1 · Semifinal": "ZC26 1v1 · Semifinal",
    "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.": "A ZC26 é uma organização independente dedicada à criação, desenvolvimento e gestão de torneios e eventos competitivos de Brawl Stars. Este evento não é afiliado, patrocinado ou endossado pela Supercell. Todos os nomes, marcas registradas, personagens e imagens do jogo pertencem exclusivamente aos seus respectivos criadores e proprietários.",
    "ZC26 ESPORTS™": "ZC26 ESPORTS™",
    "ZC26 GRAN FINAL": "ZC26 GRANDE FINAL",
    "ZC26 · 3er y 4to Lugar": "ZC26 · 3º e 4º Lugar",
    "ZC26 · Gran Final": "ZC26 · Grande Final",
    "ZC26 · Semifinal": "ZC26 · Semifinal",
    "zc26.esports.official@gmail.com": "zc26.esports.official@gmail.com",
    "Zona horaria:": "Fuso horário:",
    "© ZC26 | Todos los derechos reservados.": "© ZC26 | Todos os direitos reservados.",
    "·": "·",
    "¿Quieres apoyar a ZC26? Con una donación desde 1 dólar a través de": "Você quer apoiar a ZC26? Com uma doação a partir de 1 dólar através do",
    "Álvaro": "Álvaro",
    "Última actualización: 30 agosto, 2026": "Última atualização: 30 de agosto de 2026",
    "Última actualización: 6 dic, 2025": "Última atualização: 6 de dez. de 2025",
    "Última Clasificación": "Última Classificação",
    "Último partido importa": "A última partida importa",
    "ÚLTIMO PARTIDO IMPORTA": "A ÚLTIMA PARTIDA IMPORTA",
    "–": "-",
    "✕": "✕"
};
