// idioma/pt.js
// Diccionario Português. Clave = texto original en español (LatAm), Valor = traducción.
// Coincidencia EXACTA (recortando espacios).

var ZC_LANG_PT = {
    "% de Victoria": "% de Vitória",
    "0": "0",
    "0-2": "0-2",
    "0.0": "0,0",
    "0/11": "0/11",
    "08/09/26": "08/09/26",
    "1": "1",
    "1 ago 2026": "1 ago 2026",
    "1-2": "1-2",
    "104.0": "104,0",
    "11 Rondas": "11 Rodadas",
    "11/11": "11/11",
    "118.4": "118,4",
    "129.9": "129,9",
    "132.5": "132,5",
    "15": "15",
    "153.1": "153,1",
    "17', 26'": "17', 26'",
    "19": "19",
    "1er Lugar": "1º Lugar",
    "1er lugar · 120 pts": "1º lugar · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 0 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 0 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 2 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 2 · 120 pts",
    "1er lugar · Sets 4 - 0 · PG-PP 9 - 4 · 120 pts": "1º lugar · Sets 4 - 0 · V-D 9 - 4 · 120 pts",
    "1st": "1º",
    "1st Champion": "1º Campeão",
    "2": "2",
    "2-1": "2-1",
    "20": "20",
    "20'": "20'",
    "25%": "25%",
    "26": "26",
    "27": "27",
    "27 ago 2026": "27 ago 2026",
    "2do Lugar": "2º Lugar",
    "2do lugar · 80 pts": "2º lugar · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 6 - 4 · 80 pts": "2º lugar · Sets 3 - 1 · V-D 6 - 4 · 80 pts",
    "2do lugar · Sets 3 - 1 · PG-PP 8 - 4 · 80 pts": "2º lugar · Sets 3 - 1 · V-D 8 - 4 · 80 pts",
    "2nd": "2º",
    "2nd Runner-Up": "Terceiro lugar",
    "3": "3",
    "30 ago 2026": "30 ago 2026",
    "34": "34",
    "34'": "34'",
    "3er Lugar": "3º Lugar",
    "3er lugar · 105 pts": "3º lugar · 105 pts",
    "3er lugar · 50 pts": "3º lugar · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 6 - 2 · 50 pts": "3º lugar · Sets 3 - 1 · V-D 6 - 2 · 50 pts",
    "3er lugar · Sets 3 - 1 · PG-PP 7 - 2 · 50 pts": "3º lugar · Sets 3 - 1 · V-D 7 - 2 · 50 pts",
    "3er lugar · Sets 3 - 2 · PG-PP 7 - 6 · 50 pts": "3º lugar · Sets 3 - 2 · V-D 7 - 6 · 50 pts",
    "3er y 4to Lugar": "3º e 4º Lugar",
    "3er-4to Lugar": "3º-4º Lugar",
    "3rd-4th Place": "3º e 4º Lugar",
    "3rd-4th place": "3º-4º lugar",
    "4to Lugar": "4º Lugar",
    "4to lugar · 100 pts": "4º lugar · 100 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 4 - 4 · 45 pts": "4º lugar · Sets 2 - 2 · V-D 4 - 4 · 45 pts",
    "4to lugar · Sets 2 - 2 · PG-PP 5 - 4 · 45 pts": "4º lugar · Sets 2 - 2 · V-D 5 - 4 · 45 pts",
    "5 ago 2026": "5 ago 2026",
    "5.8": "5,8",
    "6.0": "6,0",
    "60": "60",
    "7.1": "7,1",
    "7.6": "7,6",
    "75%": "75%",
    "8 ago 2026": "8 ago 2026",
    "8'": "8'",
    "8.6": "8,6",
    "80.8": "80,8",
    "81": "81",
    "9": "9",
    "9.4": "9,4",
    "94.8": "94,8",
    "98.0": "98,0",
    "A nivel individual, el jugador Taikisha fue reconocido como la figura más destacada del evento por su brillante rendimiento a lo largo de las partidas, recibiendo una bonificación especial por su aporte al equipo.": "A nível individual, o jogador Taikisha foi reconhecido como a figura mais destacada do evento por seu brilhante desempenho ao longo das partidas, recebendo um bônus especial por sua contribuição à equipe.",
    "Abrir menú": "Abrir menu",
    "Actividad": "Atividade",
    "Activo": "Ativo",
    "Además, contaremos con un equipo de moderación dedicado a revisar cada partida de cerca, asegurando que el ambiente se mantenga limpio, respetuoso y ordenado durante los días de competencia.": "Além disso, contaremos com uma equipe de moderação dedicada a revisar cada partida de perto, garantindo que o ambiente se mantenha limpo, respeitoso e ordenado durante os dias de competição.",
    "Agradecemos la participación de todos los competidores y les invitamos a mantenerse atentos a las próximas ediciones.": "Agradecemos a participação de todos os competidores e convidamos vocês a ficarem atentos às próximas edições.",
    "Ajuste de ponderación por tipo de evento:": "Ajuste de ponderação por tipo de evento:",
    "Al conseguir los créditos necesarios, se abrirá una pantalla especial donde se mostrarán los personajes disponibles. Al tocar la pantalla, las opciones se irán eliminando una a una hasta revelar al personaje obtenido.": "Ao conseguir os créditos necessários, uma tela especial será aberta onde os personagens disponíveis serão mostrados. Ao tocar na tela, as opções vão se eliminando uma a uma até revelar o personagem obtido.",
    "Alineaciones": "Escalações",
    "Antes del inicio de los enfrentamientos en la gran final, ambos equipos aplicaron su estrategia en la fase de vetos. Quedaron excluidos de la partida los personajes Belle, Spike, Bibi y Nori, lo que obligó a las escuadras a replantear sus composiciones tácticas para la serie decisiva.": "Antes do início dos confrontos na grande final, ambas as equipes aplicaram sua estratégia na fase de vetos. Ficaram excluídos da partida os personagens Belle, Spike, Bibi e Nori, o que obrigou as equipes a reformularem suas composições táticas para a série decisiva.",
    "Apoyamos y síguenos en nuestras redes sociales": "Apoie-nos e siga-nos nas nossas redes sociais",
    "Arranca la nueva temporada: así se reinicia la puntuación de cada jugador": "Começa a nova temporada: veja como a pontuação de cada jogador é reiniciada",
    "As Combat": "Combate Ás",
    "ASIA": "ÁSIA",
    "Asimismo, el veintinueve de agosto se entregarán mil quinientos créditos como compensación por los ajustes en el sistema. Los jugadores podrán decidir si utilizar estos créditos antes de la actualización para conseguir el personaje que estén desbloqueando actualmente o guardarlos para el nuevo sistema aleatorio.": "Da mesma forma, no dia vinte e nove de agosto serão entregues mil e quinhentos créditos como compensação pelos ajustes no sistema. Os jogadores poderão decidir se usam esses créditos antes da atualização para conseguir o personagem que estão desbloqueando atualmente ou guardá-los para o novo sistema aleatório.",
    "Asist.:": "Assist.:",
    "Asistencias": "Assistências",
    "Así se jugó la final: Leviatán se impuso 3-1 en los mapas": "Assim foi jogada a final: Leviatán venceu por 3-1 nos mapas",
    "Ataques": "Ataques",
    "Aug 8, 26": "8 de ago., 26",
    "Aún no hay estadísticas de defensa registradas para este partido.": "Ainda não há estatísticas de defesa registradas para esta partida.",
    "Balance global interregional: elimina el sesgo regional. Un equipo de LATAM o Asia tiene exactamente la misma oportunidad de escalar al Top 1 Global que un equipo de Europa o Norteamérica al ganar torneos de similar categoría.": "Equilíbrio global inter-regional: elimina o viés regional. Uma equipe da LATAM ou Ásia tem exatamente a mesma oportunidade de subir ao Top 1 Global que uma equipe da Europa ou América do Norte ao vencer torneios de categoria semelhante.",
    "Baneos globales": "Banimentos globais",
    "Belle rock": "Rocha da Belle",
    "belle y spike": "Belle e Spike",
    "Beneficios para el ecosistema Esports de Brawl Stars": "Benefícios para o ecossistema de Esports de Brawl Stars",
    "Bibi y Nori": "Bibi e Nori",
    "Brawl Ball": "Fute-Brawl",
    "Brawl Stars Oficial": "Brawl Stars Oficial",
    "Brawl Stars · Agosto 8 de 2026": "Brawl Stars · 8 de agosto de 2026",
    "BRAWLER BLAST": "EXPLOSÃO BRAWLER",
    "Brawlers principales": "Brawlers principais",
    "BSC, AUG 8": "BSC, 8 DE AGO.",
    "Buscar por nombre, ID o país...": "Pesquisar por nome, ID ou país...",
    "Cada descarte otorgará fragmentos de gemas que se convertirán directamente en mejoras para el personaje, como puntos de fuerza, gadgets, habilidades estelares, engranajes o hipercargas. Siempre se asegurará al menos un nivel de fuerza, con la posibilidad de obtener un personaje mejorado al máximo.": "Cada descarte concederá fragmentos de gemas que se converterão diretamente em melhorias para o personagem, como pontos de força, gadgets, poderes estrela, engrenagens ou hipercargas. Sempre será assegurado pelo menos um nível de força, com a possibilidade de obter um personagem melhorado ao máximo.",
    "Calificaciones de los jugadores (0/11) basadas en los datos de los partidos": "Avaliações dos jogadores (0/11) com base nos dados das partidas",
    "Calificación del jugador": "Avaliação do jogador",
    "Campeones a lo largo de los torneos ZC26": "Campeões ao longo dos torneios ZC26",
    "Campeón": "Campeão",
    "Campeón · 500 pts · +25 Estelar (Set 1)": "Campeão · 500 pts · +25 Estelar (Set 1)",
    "Campeón · 500 pts · +25 Estelar (Set 3)": "Campeão · 500 pts · +25 Estelar (Set 3)",
    "Campeón · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP": "Campeão · 500 pts · +25 Estelar (Set 4) · +25 Bono MVP",
    "Campeón · Suplente (no disputó rondas)": "Campeão · Suplente (no disputó rondas)",
    "Cero penalizaciones por inactividad injusta: el ranking no degrada puntos artificialmente por el paso del tiempo, eliminando la necesidad de competir en eventos menores solo para \"mantener la posición\".": "Zero penalizações por inatividade injusta: o ranking não reduz pontos artificialmente com a passagem do tempo, eliminando a necessidade de competir em eventos menores só para \"manter a posição\".",
    "Champion": "Campeão",
    "Claridad en la selección de Seeds: permite a los organizadores de torneos (TOs) sembrar los brackets de torneos 1v1 y 3v3 de forma justa, evitando cruces de alto nivel en las primeras rondas de una clasificatoria.": "Clareza na seleção de cabeças de chave: permite que os organizadores de torneios (TOs) montem os brackets de torneios 1v1 e 3v3 de forma justa, evitando confrontos de alto nível nas primeiras rodadas de uma classificatória.",
    "Clasificación actual": "Classificação atual",
    "Clasificación ZC26 - Últimas noticias": "Classificação ZC26 - Últimas notícias",
    "Coach": "Treinador",
    "COMENTARIOS": "COMENTÁRIOS",
    "Con estos resultados, la tabla general de posiciones quedó encabezada por Leviatán Esports en el primer lugar, escoltado por el subcampeón en la segunda casilla y cerrando el podio con el tercer puesto del torneo.": "Com esses resultados, a tabela geral de posições ficou encabeçada pela Leviatán Esports em primeiro lugar, escoltada pelo vice-campeão na segunda posição e fechando o pódio com o terceiro lugar do torneio.",
    "Contacto": "Contato",
    "Contacto comercial y soporte:": "Contato comercial e suporte:",
    "Contribucion": "Contribuição",
    "Contribución total": "Contribuição total",
    "Copyrights © ZC ESPORTS 2026": "Direitos autorais © ZC ESPORTS 2026",
    "CREDITOS": "CRÉDITOS",
    "Cronología": "Cronologia",
    "Créditos aprox.": "Créditos aprox.",
    "Cuando se añada un nuevo personaje al juego, este se sumará a la lista de su respectiva rareza y podrá aparecer en Brawler Blast, aunque no se podrá priorizar su desbloqueo inmediato.": "Quando um novo personagem for adicionado ao jogo, este se somará à lista de sua respectiva raridade e poderá aparecer no Brawler Blast, embora não se possa priorizar seu desbloqueio imediato.",
    "Datos de Brawl Stars": "Dados de Brawl Stars",
    "Datos destacados": "Dados em destaque",
    "Defensas": "Defesas",
    "Derrotas": "Derrotas",
    "Descenso": "Queda",
    "Después de ese evento, nos tomamos un tiempo fuera de las canchas para planificar todo con calma, pero la espera terminó y estamos de vuelta oficialmente con una nueva entrega de la ZC26. En esta oportunidad, volveremos a medir el nivel de todos en la modalidad de tres contra tres dentro de Brawl Stars.": "Depois desse evento, tiramos um tempo fora das quadras para planejar tudo com calma, mas a espera acabou e estamos de volta oficialmente com uma nova edição da ZC26. Desta vez, voltaremos a medir o nível de todos na modalidade de três contra três dentro do Brawl Stars.",
    "Discord": "Discord",
    "doble swoosh": "Duplo Swoosh",
    "Donde dr es la diferencia de puntos entre ambos competidores: dr = [P_antes del Equipo A − P_antes del Equipo B].": "Onde dr é a diferença de pontos entre os dois competidores: dr = [P_antes da Equipe A − P_antes da Equipe B].",
    "DPS:": "DPS:",
    "Edición 4": "Edição 4",
    "Ejemplo:": "Exemplo:",
    "El desarrollo del encuentro final mostró un desempeño firme por parte de Leviatán Esports, superando a su rival por un marcador de tres sets a uno. El primer set se jugó en el mapa Neumáticos Maniáticos, donde Leviatán tomó la ventaja inicial con una victoria limpia de dos a cero.": "O desenvolvimento do encontro final mostrou um desempenho firme por parte da Leviatán Esports, superando seu rival por um placar de três sets a um. O primeiro set foi jogado no mapa Pneus Pirados, onde a Leviatán assumiu a vantagem inicial com uma vitória limpa de dois a zero.",
    "El encuentro terminó.": "A partida terminou.",
    "el Equipo A tiene 1300 puntos y vence en una Clasificatoria Abierta al Equipo B, que tiene 1500 puntos.": "a Equipe A tem 1300 pontos e vence a Equipe B, que tem 1500 pontos, em uma Classificatória Aberta.",
    "El método Elo suma o resta puntos al total acumulado de cada jugador o equipo en función de los resultados de sus partidas (en lugar de promediar). Los puntos ganados o perdidos se determinan según el nivel del rival, garantizando que vencer a un equipo o jugador de rango superior otorgue una recompensa significativamente mayor.": "O método Elo soma ou subtrai pontos do total acumulado de cada jogador ou equipe em função dos resultados das suas partidas (em vez de fazer uma média). Os pontos ganhos ou perdidos são determinados de acordo com o nível do rival, garantindo que vencer uma equipe ou jogador de nível superior conceda uma recompensa significativamente maior.",
    "El nuevo modelo para calcular el Ranking Mundial de Brawl Stars (BWR) fue desarrollado tras analizar el rendimiento de los equipos en modos 1v1 y 3v3 durante múltiples temporadas, probando y discutiendo diversos algoritmos.": "O novo modelo para calcular o Ranking Mundial de Brawl Stars (BWR) foi desenvolvido após analisar o desempenho das equipes nos modos 1v1 e 3v3 durante múltiplas temporadas, testando e discutindo diversos algoritmos.",
    "El objetivo principal es contar con un sistema intuitivo, transparente y preciso para medir la fuerza real de los jugadores y clubes en la escena competitiva, garantizando oportunidades equitativas para que las organizaciones de todas las regiones (LATAM, Europa, NA, Asia, etc.) asciendan en la tabla global.": "O objetivo principal é contar com um sistema intuitivo, transparente e preciso para medir a força real dos jogadores e clubes na cena competitiva, garantindo oportunidades equitativas para que as organizações de todas as regiões (LATAM, Europa, NA, Ásia, etc.) subam na tabela global.",
    "El sistema Camino Starr será reemplazado por Brawler Blast": "O sistema Caminho Starr será substituído por Brawler Blast",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast": "O sistema Trilha Estelar será substituído por uma nova mecânica chamada Explosão Brawler",
    "El sistema Camino Starr será reemplazado por una nueva mecánica llamada Brawler Blast. Con este cambio, al reunir la cantidad de créditos requerida, se desbloqueará un personaje de manera aleatoria dentro de una determinada rareza, otorgando además progresión extra para dicho personaje.": "O sistema Caminho Starr será substituído por uma nova mecânica chamada Brawler Blast. Com esta mudança, ao reunir a quantidade de créditos necessária, um personagem será desbloqueado de maneira aleatória dentro de uma determinada raridade, concedendo além disso progressão extra para o referido personagem.",
    "El torneo oficial de tres contra tres de Brawl Stars ha llegado a su final, consagrando a Leviatán Esports como el gran campeón de esta edición inaugural. La jornada de competencia estuvo marcada por un nivel técnico sobresaliente y series de alta intensidad en cada una de las rondas disputadas.": "O torneio oficial de três contra três do Brawl Stars chegou ao fim, consagrando a Leviatán Esports como a grande campeã desta edição inaugural. A jornada de competição foi marcada por um nível técnico sobressalente e séries de alta intensidade em cada uma das rodadas disputadas.",
    "Eliminaciones (Kills)": "Eliminações (Abates)",
    "EMEA": "EMEA",
    "En el segundo mapa, Roca de Belle, el conjunto rival logró responder y empatar la serie al adjudicarse el punto con un resultado de dos a uno. Sin embargo, Leviatán recuperó el control de las acciones en el tercer mapa, Arbustos Frondosos, imponiéndose dos a uno en un duelo muy disputado, y finalmente cerró el campeonato en el mapa Doble Swoosh con un categórico dos a cero.": "No segundo mapa, Rocha da Belle, o conjunto rival conseguiu responder e empatar a série ao conquistar o ponto com um resultado de dois a um. No entanto, a Leviatán recuperou o controle das ações no terceiro mapa, Arbustos Densos, impondo-se dois a um em um duelo muito disputado, e finalmente fechou o campeonato no mapa Giro Duplo com um categórico dois a zero.",
    "Equipo": "Equipe",
    "Equipo A: P = 1300 + 25 × (1 − (1 / (10^(−(1300−1500)/600) + 1)))": "Equipe A: P = 1300 + 25 × (1 − (1 / (10^(−(1300−1500)/600) + 1)))",
    "Equipo B: P = 1500 + 25 × (0 − (1 / (10^(−(1500−1300)/600) + 1)))": "Equipe B: P = 1500 + 25 × (0 − (1 / (10^(−(1500−1300)/600) + 1)))",
    "Equipo de Apoyo": "Equipe de Apoio",
    "Estado": "Status",
    "Estadísticas": "Estatísticas",
    "Estadísticas clave": "Estatísticas principais",
    "Estadísticas del partido": "Estatísticas da partida",
    "Estadísticas generales del partido": "Estatísticas gerais da partida",
    "Estadísticas y rendimiento competitivo": "Estatísticas e desempenho competitivo",
    "Estimada comunidad, nos alegra mucho ponernos en contacto con ustedes para compartir varias novedades importantes sobre el desarrollo de nuestros torneos. Como bien recordarán, en la última edición el equipo de Levantan Esports se quedó con el primer lugar tras una excelente participación.": "Estimada comunidade, estamos muito felizes em entrar em contato com vocês para compartilhar várias novidades importantes sobre o desenvolvimento dos nossos torneios. Como bem devem se lembrar, na última edição a equipe da Levantan Esports ficou com o primeiro lugar após uma excelente participação.",
    "Eventos:": "Eventos:",
    "Exención de penalización: sin pérdida de puntos al ser eliminado en las rondas finales K.O. de eventos presenciales o Majors.": "Isenção de penalização: sem perda de pontos ao ser eliminado nas rodadas finais K.O. de eventos presenciais ou Majors.",
    "Faltas": "Faltas",
    "Fecha": "Data",
    "Filtro": "Filtro",
    "Filtros": "Filtros",
    "Fin": "Fim",
    "Finalized": "Finalizado",
    "Finished": "Encerrado",
    "Ganancias aprox.": "Ganhos aprox.",
    "Gem Grab": "Pique-Gema",
    "Gmail": "Gmail",
    "GRAN FINAL": "GRANDE FINAL",
    "Gran Final": "Grande Final",
    "Gran Final 🏆": "Grande Final 🏆",
    "Habilidades": "Habilidades",
    "Heist": "Roubo",
    "Highlights": "Melhores momentos",
    "Historias destacadas": "Histórias de destaque",
    "Home": "Início",
    "HOME": "INÍCIO",
    "I = 05 — Showmatches o partidas de exhibición sin invitación oficial": "I = 05 — Showmatches ou partidas de exibição sem convite oficial",
    "I = 10 — Partidas de exhibición / Scrims oficiales transmitidas": "I = 10 — Partidas de exibição / Scrims oficiais transmitidas",
    "I = 15 — Fase de grupos de Ligas Regionales Semiprofesionales": "I = 15 — Fase de grupos de Ligas Regionais Semiprofissionais",
    "I = 25 — Clasificatorias Abiertas (Open Qualifiers) a Torneos Majors o BSC (Brawl Stars Championship)": "I = 25 — Classificatórias Abertas (Open Qualifiers) para Torneios Majors ou BSC (Brawl Stars Championship)",
    "I = 25 — Playoffs y Finales de Ligas Regionales": "I = 25 — Playoffs e Finais de Ligas Regionais",
    "I = 35 — Fase de grupos de Torneos Internacionales / Majors hasta cuartos de final": "I = 35 — Fase de grupos de Torneios Internacionais / Majors até as quartas de final",
    "I = 40 — Fase de grupos de Torneos Internacionales desde cuartos de final en adelante": "I = 40 — Fase de grupos de Torneios Internacionais a partir das quartas de final",
    "I = 50 — Fase final del Mundial / World Finals hasta cuartos de final": "I = 50 — Fase final do Mundial / World Finals até as quartas de final",
    "I = 60 — Fase final del Mundial / World Finals desde cuartos de final hasta la Gran Final": "I = 60 — Fase final do Mundial / World Finals a partir das quartas de final até a Grande Final",
    "I:": "I:",
    "IDs alternos": "IDs alternativos",
    "Imagen no disponible": "Imagem não disponível",
    "Immortal Combat": "Combate Imortal",
    "Importancia del partido": "Importância da partida",
    "importancia del torneo o enfrentamiento:": "importância do torneio ou confronto:",
    "Inactivo": "Inativo",
    "Información": "Informação",
    "Información general": "Informações gerais",
    "iXCross": "iXCross",
    "iXLCross": "iXLCross",
    "JOAR": "JOAR",
    "Juanjo": "Juanjo",
    "Juanjoxd": "Juanjoxd",
    "Jugador": "Jogador",
    "Jugador Sorpresa": "Jogador Surpresa",
    "Julio": "Julio",
    "Juliocr36D": "Juliocr36D",
    "Kills:": "Abates:",
    "Knockout": "Nocaute",
    "L. Puppies Represent · Titulares": "L. Puppies Represent · Titulares",
    "La Clasificación ZC26 se determina utilizando el Modelo Elo. Este método suma o resta puntos por partidos al total de puntos existente de un equipo. Los puntos que se suman o restan vienen determinados en parte por:": "A Classificação ZC26 é determinada utilizando o Modelo Elo. Este método soma ou subtrai pontos por partida ao total de pontos existente de uma equipe. Os pontos que se somam ou subtraem são determinados em parte por:",
    "La estructura del torneo está pensada para mantener la emoción de principio a fin, ya que será una competencia intensa donde solo un equipo logrará llevarse el trofeo de campeón. Sabemos que la exigencia es alta, por lo que esperamos ver partidas muy disputadas entre los mejores grupos que se presenten.": "A estrutura do torneio foi pensada para manter a emoção do início ao fim, pois será uma competição intensa onde apenas uma equipe conseguirá levar o troféu de campeã. Sabemos que a exigência é alta, por isso esperamos ver partidas muito disputadas entre os melhores grupos que se apresentarem.",
    "La FIFA adaptó este formato bajo el nombre de algoritmo \"SUMA\", el cual adaptamos directamente para los formatos 1v1 (Duels / Duelos) y 3v3 (Atrapagemas, Balón Brawl, Zona Restringida, Caza de Gemas, etc.):": "A FIFA adaptou este formato sob o nome de algoritmo \"SOMA\", o qual adaptamos diretamente para os formatos 1v1 (Duels / Duelos) e 3v3 (Assalto a Gemas, Brawl Ball, Nocaute, Caça ao Tesouro, etc.):",
    "La fórmula base": "A fórmula base",
    "La fórmula base del algoritmo SUMA es:": "A fórmula base do algoritmo SOMA é:",
    "La hazaña de RobertBV: 100% de victorias sin perder una sola ronda": "O feito de RobertBV: 100% de vitórias sem perder uma única rodada",
    "La ZC26 vuelve este septiembre": "O ZC26 retorna neste mês de setembro",
    "Leaderboard": "Leaderboard",
    "leafy bushes": "Arbustos Frondosos",
    "LEV": "LEV",
    "LEV WINNER": "VITÓRIA DA LEV",
    "LEVIATÁN ESPORT · Titulares": "LEVIATÁN ESPORT · Titulares",
    "LEVIATÁN ESPORTS se corona CAMPEÓN de la ZC26 Agosto": "LEVIATÁN ESPORTS sagra-se CAMPEÃ do ZC26 de Agosto",
    "LEVIATÁN ESPORTS toma el primer puesto tras coronarse campeón de la ZC26 Agosto": "LEVIATÁN ESPORTS assume o primeiro lugar após ser coroada campeã da ZC26 Agosto",
    "Lo más destacado del ranking": "Destaques da classificação",
    "Logros": "Conquistas",
    "Los invitamos a ponerse de acuerdo con sus compañeros, armar sus alineaciones con tiempo y empezar a practicar. En los próximos días seguiremos publicando más detalles sobre los horarios y la forma de registro, así que manténganse atentos a los anuncios.": "Convidamos vocês a entrarem em acordo com seus companheiros, montarem suas escalações com antecedência e começarem a praticar. Nos próximos dias continuaremos publicando mais detalhes sobre os horários e a forma de registro, portanto fiquem atentos aos anúncios.",
    "LPR": "LPR",
    "Lugar:": "Local:",
    "Marcador": "Placar",
    "Master Combat": "Combate Mestre",
    "MATCHES, AUG 8": "PARTIDAS, 8 DE AGO.",
    "Mayor a menor": "Maior para menor",
    "Mayor bajada": "Maior queda",
    "Mayor subida": "Maior subida",
    "Mayor valor a las rondas de eliminación directa (Playoffs) frente a las fases de grupos o clasificatorias abiertas.": "Maior valor às rodadas de eliminação direta (Playoffs) em relação às fases de grupos ou classificatórias abertas.",
    "Mejor Clasificación": "Melhor Classificação",
    "Mejor contribución": "Melhor contribuição",
    "Mejor jugada": "Melhor jogada",
    "MEJOR JUGADA": "MELHOR JOGADA",
    "Menor a mayor": "Menor para maior",
    "Menor impacto en partidas de exhibición o scrims oficiales; mayor impacto en fases finales de torneos Mayor/Championship.": "Menor impacto em partidas de exibição ou scrims oficiais; maior impacto nas fases finais de torneios Major/Championship.",
    "Modalidad: 3 vs 3 · Bo5 · Tier S": "Modalidade: 3 vs 3 · Bo5 · Tier S",
    "Momentos de la BSC de la ZC26™": "Momentos da BSC da ZC26™",
    "Mostrar Clasificación completa": "Mostrar classificação completa",
    "Mostrar menos": "Mostrar menos",
    "Mostrar más": "Mostrar mais",
    "mostrar más": "mostrar mais",
    "Movimiento": "Movimento",
    "MVP:": "MVP:",
    "Más info.": "Mais informações",
    "Más información sobre": "Mais informações sobre",
    "Más información sobre cómo se calcula la Clasificación": "Mais informações sobre como se calcula a Classificação",
    "Más partidos": "Mais partidas",
    "MÁS ZC26": "MAIS ZC26",
    "N/A": "N/D",
    "NA": "NA",
    "Nacaru": "Nacaru",
    "Nacimiento": "Nascimento",
    "Nacionalidad": "Nacionalidade",
    "Nada": "Nada",
    "NEW": "NOVO",
    "Ninja": "Ninja",
    "Nivel general de juego mostrado en competencia, según su balance de victorias en sets y mapas.": "Nível geral de jogo demonstrado em competição, de acordo com o seu saldo de vitórias em sets e mapas.",
    "Nivel relativo del jugador": "Nível relativo do jogador",
    "No hace falta ser un experto en competencias para sumarse; las guías y las instrucciones están redactadas de forma sencilla para que todos sepan exactamente cómo inscribirse, cómo reportar sus resultados y cómo avanzar en cada fase.": "Não é preciso ser um especialista em competições para participar; os guias e as instruções estão redigidos de forma simples para que todos saibam exatamente como se inscrever, como relatar seus resultados e como avançar em cada fase.",
    "No hay logros registrados": "Sem conquistas registradas",
    "No hay partidas con ese filtro": "Não há partidas com esse filtro",
    "No se encontró ningún jugador con estos filtros.": "Nenhum jogador encontrado com estes filtros.",
    "No se encontró ningún jugador.": "Nenhum jogador foi encontrado.",
    "No se pudo cargar el archivo de idioma:": "Não foi possível carregar o arquivo de idioma:",
    "Novedades de la Clasificación": "Novidades da Classificação",
    "Nueva clasificación más alta": "Nova classificação mais alta",
    "Nuevo": "Novo",
    "Ocultar Clasificación completa": "Ocultar Classificação completa",
    "Orden": "Ordem",
    "Organización del Evento: ZC26 BSC (Brawl Stars Championship)": "Organização do Evento: ZC26 BSC (Campeonato de Brawl Stars)",
    "Otras novedades": "Outras novidades",
    "Otro punto en el que pusimos mucho esfuerzo fue en la claridad del reglamento. Queremos que cualquier persona que tenga ganas de jugar pueda entender el formato sin complicaciones, incluso si es la primera vez que participa en un torneo de este tipo.": "Outro ponto no qual colocamos muito esforço foi na clareza do regulamento. Queremos que qualquer pessoa que tenha vontade de jogar possa entender o formato sem complicações, mesmo se for a primeira vez que participa de um torneio desse tipo.",
    "P = P_antes + I × (W − We)": "P = P_antes + I × (W − We)",
    "P_antes:": "P_antes:",
    "P_inicial = 1600 − (R − 1) × 4": "P_inicial = 1600 − (R − 1) × 4",
    "Para esta edición decidimos renovar varias cosas. Incorporamos nuevas reglas y mecánicas de juego que buscan equilibrar la cancha para todos los participantes. La idea principal es que cada equipo compita en igualdad de condiciones, sin ventajas injustas para nadie.": "Para esta edição decidimos renovar várias coisas. Incorporamos novas regras e mecânicas de jogo que buscam equilibrar o campo para todos os participantes. A principal ideia é que cada equipe compita em igualdade de condições, sem vantagens injustas para ninguém.",
    "Para iniciar una nueva temporada competitiva, los equipos y jugadores se posicionan de forma homogénea en una escala de 800 a 1600 puntos según sus resultados del año anterior. La diferencia base entre cada puesto del ranking es de 4 puntos.": "Para iniciar uma nova temporada competitiva, as equipes e jogadores são posicionados de forma homogênea em uma escala de 800 a 1600 pontos de acordo com os seus resultados do ano anterior. A diferença base entre cada posição do ranking é de 4 pontos.",
    "Partidas (PG-PP):": "Partidas (V-D):",
    "Partidas recientes": "Partidas recentes",
    "Partners": "Parceiros",
    "PARTNERS": "PARCEIROS",
    "PayPal": "PayPal",
    "País": "País",
    "Peor clasificación": "Pior classificação",
    "PG-PP": "V-D",
    "Player Tag / Player ID": "Player Tag / Player ID",
    "Por confirmar": "A confirmar",
    "Porcentaje de victorias": "Porcentagem de vitórias",
    "Posiciones": "Tabela",
    "Posición en el ranking": "Posição no ranking",
    "Posición promedio": "Posição média",
    "Potencial": "Potencial",
    "Premia el rendimiento constante: elimina el estancamiento de puntos y permite que las sorpresas (upsets) de equipos emergentes en modos 1v1 o 3v3 se reflejen de inmediato en la tabla general.": "Premia o desempenho constante: elimina a estagnação de pontos e permite que as surpresas (upsets) de equipes emergentes nos modos 1v1 ou 3v3 se reflitam de imediato na tabela geral.",
    "PREMIOS": "PRÊMIOS",
    "Proceso de conversión inicial (Seeding de Temporada)": "Processo de conversão inicial (Seeding da Temporada)",
    "Promedio de puntos por torneo": "Média de pontos por torneio",
    "Promedio DPS de Equipo": "Média de DPS da Equipe",
    "Protección en Knockout de Finals: los equipos eliminados en los Brackets de Eliminación Directa de un torneo presencial o Major no pierden puntos de ranking, incluso frente a un rival de menor puntaje (si W − We es menor que 0, entonces P = P_antes). Esto protege el esfuerzo de los equipos por haber clasificado a las etapas finales presenciales.": "Proteção no Knockout das Finais: as equipes eliminadas nos Brackets de Eliminação Direta de um torneio presencial ou Major não perdem pontos de ranking, mesmo diante de um rival com pontuação menor (se W − We for menor que 0, então P = P_antes). Isso protege o esforço das equipes por terem se classificado para as etapas finais presenciais.",
    "Próxima actualización oficial: 25 septiembre 2026": "Próxima atualização oficial: 25 de setembro de 2026",
    "pts": "pts",
    "puedes obtener beneficios dentro de la comunidad.": "você pode obter benefícios dentro da comunidade.",
    "Punto de campeonato": "Ponto de campeonato",
    "PUNTO DE CAMPEONATO": "PONTO DE CAMPEONATO",
    "puntos del jugador o equipo antes del set/partida.": "pontos do jogador ou equipe antes do set/partida.",
    "Puntos totales:": "Pontos totais:",
    "Qué tan alto puede llegar el jugador, según sus puntos acumulados frente al máximo del ranking.": "Até onde o jogador pode chegar, de acordo com os pontos acumulados em relação ao máximo do ranking.",
    "Qué tan reconocido y famoso es el jugador a nivel internacional, más allá de su liga local.": "O quão reconhecido e famoso é o jogador a nível internacional, além da sua liga local.",
    "Rango Mítico": "Rank Mítico",
    "Ranking": "Classificação",
    "RANKING": "CLASSIFICAÇÃO",
    "Ranking 1vs1": "Ranking 1vs1",
    "Ranking 3vs3": "Ranking 3vs3",
    "Ranking General": "Ranking Geral",
    "Reconocimientos especiales": "Reconhecimentos especiais",
    "Redes oficiales:": "Redes oficiais:",
    "Redes sociales": "Redes sociais",
    "Región": "Región",
    "Reglas especiales para el competitivo de Brawl Stars": "Regras especiais para o competitivo de Brawl Stars",
    "Regresa la ZC26 Brawl Stars este mes de septiembre": "O ZC26 de Brawl Stars retorna neste mês de setembro",
    "Regresar": "Voltar",
    "Reputación Int.": "Reputação Int.",
    "Reputación Internacional": "Reputação Internacional",
    "Restablecer filtros": "Redefinir filtros",
    "Resultado del partido": "Resultado da partida",
    "resultado del set/partida — 1 = victoria clara (ej. 2-0 o 3-0 en sets); 0.5 = empate/desempate por objetivos; 0 = derrota.": "resultado do set/partida — 1 = vitória clara (ex. 2-0 ou 3-0 em sets); 0,5 = empate/desempate por objetivos; 0 = derrota.",
    "Resultado esperado del partido": "Resultado esperado da partida",
    "resultado esperado según la diferencia de nivel, calculado como:": "resultado esperado de acordo com a diferença de nível, calculado como:",
    "Resultado: el Equipo A suma 17 puntos (P = 1317) y el Equipo B pierde 17 puntos (P = 1483).": "Resultado: a Equipe A soma 17 pontos (P = 1317) e a Equipe B perde 17 pontos (P = 1483).",
    "RESUMEN AGOSTO": "RESUMO DE AGOSTO",
    "Rol": "Função",
    "Ronda 1": "Rodada 1",
    "Ronda 2": "Rodada 2",
    "Rondas Ganadas (Sets)": "Rodadas Vencidas (Sets)",
    "Rondas:": "Rodadas:",
    "Récord de mapas/modos (PG-PP)": "Recorde de mapas/modos (V-D)",
    "Récord de sets (G-P)": "Recorde de sets (V-D)",
    "SA": "SA",
    "SALON DE LA FAMA": "HALL DA FAMA",
    "Salón de la fama": "Hall da Fama",
    "Salón de la Fama": "Hall da Fama",
    "Sanciones": "Punições",
    "Se actualiza con cada contribucion a ZC26": "É atualizado com cada contribuição para a ZC26",
    "Se actualiza con cada torneo de ZC26": "É atualizado com cada torneio da ZC26",
    "Según los datos de los partidos": "Segundo os dados das partidas",
    "Seleccion completa": "Seleção completa",
    "Semana de movimientos: varios equipos entran al Top 10 de la Clasificación": "Semana de movimentações: várias equipes entram no Top 10 da Classificação",
    "Sembrado #100: P_inicial = 1204": "Cabeça de chave #100: P_inicial = 1204",
    "Sembrado #200: P_inicial = 804": "Cabeça de chave #200: P_inicial = 804",
    "Sembrado #3: P_inicial = 1592": "Cabeça de chave #3: P_inicial = 1592",
    "Semifinal": "Semifinal",
    "Servidores Globales, Brawl Stars": "Servidores Globais, Brawl Stars",
    "Set Marcado:": "Set Marcado:",
    "Sets": "Sets",
    "Sets (G-P):": "Sets (V-D):",
    "Sets ajustados (Bracket de Perdedores / Tiebreaker): un set decidido en la última partida decisiva (ej. 2-1 en sets o en tiempo suplementario de Balón Brawl) otorga un valor de victoria parcial para el ganador y no penaliza severamente al perdedor. Si el set se decide en Tiebreaker estricto: W del equipo ganador = 0.75, W del equipo perdedor = 0.5.": "Sets ajustados (Bracket de Perdedores / Tiebreaker): um set decidido na última partida decisiva (ex. 2-1 em sets ou na prorrogação de Brawl Ball) concede um valor de vitória parcial ao vencedor e não penaliza severamente o perdedor. Se o set for decidido em Tiebreaker estrito: W da equipe vencedora = 0,75, W da equipe perdedora = 0,5.",
    "Si deseas solicitar alguna modificación sobre tu identidad dentro de la página — como corrección de nombre, región, fecha de nacimiento, apodo, redes sociales u otro dato asociado a tu perfil — por favor contáctanos a través de los medios oficiales indicados arriba.": "Caso deseje solicitar alguma modificação sobre sua identidade na página — como correção de nome, região, data de nascimento, apelido, redes sociais ou outro dado associado ao seu perfil — por favor, entre em contato conosco através dos meios oficiais indicados acima.",
    "Silenciar sonidos": "Silenciar sons",
    "Sin partidas registradas": "Sem partidas registradas",
    "Sobre la nueva fórmula": "Sobre a nova fórmula",
    "Subcampeón": "Vice-campeão",
    "Subcampeón · 250 pts": "Vice-campeão · 250 pts",
    "Subcampeón · 250 pts · +25 Estelar (Set 2)": "Vice-campeão · 250 pts · +25 Estelar (Set 2)",
    "Subida": "Subida",
    "Suplente · LEV": "Reserva · LEV",
    "Suplentes": "Reservas",
    "Sí": "Sim",
    "TA:": "CA:",
    "Taikisha, elegido MVP de la Gran Final": "Taikisha, eleito MVP da Grande Final",
    "TAIKISHA, MVP": "TAIKISHA, MVP",
    "Taikisha, MVP 🏆": "Taikisha, MVP 🏆",
    "También podría interesarle...": "Você também pode se interessar por...",
    "Tarjetas Amarillas": "Cartões Amarelos",
    "Tarjetas Rojas": "Cartões Vermelhos",
    "Tier": "Tier",
    "Tier-A": "Tier-A",
    "Tier-B": "Tier-B",
    "Tier-S": "Tier-S",
    "TikTok": "TikTok",
    "tire maniacs": "Maníacos por Pneus",
    "Titular": "Titular",
    "Titular · Capitán": "Titular · Capitão",
    "Todas las novedades de la Clasificación": "Todas as novidades da Classificação",
    "Todo el contenido publicado en esta página se ofrece de forma gratuita e informativa. No está permitido redistribuir, copiar ni reutilizar el contenido original sin autorización expresa de ZC26. La información se proporciona sin garantías y puede actualizarse sin previo aviso.": "Todo o conteúdo publicado nesta página é oferecido de forma gratuita e informativa. Não é permitido redistribuir, copiar ou reutilizar o conteúdo original sem autorização expressa da ZC26. As informações são fornecidas sem garantias e podem ser atualizadas sem aviso prévio.",
    "Todos": "Todos",
    "Todos los horarios corresponden a la hora estándar de Sudamérica": "Todos os horários correspondem à hora padrão da América do Sul",
    "Todos los horarios corresponden a la hora estándar regional": "Todos os horários correspondem à hora padrão regional",
    "Todos los partidos": "Todas as partidas",
    "Top 1 Global (Sembrado #1): P_inicial = 1600": "Top 1 Global (Cabeça de chave #1): P_inicial = 1600",
    "Torneo": "Torneio",
    "Torneo virtual \"ZC26 AUGT8\", manejado por el equipo del soporte": "Torneio virtual \"ZC26 AUGT8\", gerenciado pela equipe de suporte",
    "TR:": "CV:",
    "Términos de uso": "Termos de uso",
    "Títulos:": "Títulos:",
    "Ver completo": "Ver completo",
    "Ver estadisticas": "Ver estatísticas",
    "Ver todos los partidos": "Ver todas as partidas",
    "Versión 2.0.9.6": "Versão 2.0.9.6",
    "Versión 4.2.0.19": "Versão 4.2.0.19",
    "Victorias": "Vitórias",
    "Volver arriba": "Voltar ao topo",
    "W:": "W:",
    "Watch Game": "Assistir Partida",
    "We = 1 / (10^(−dr/600) + 1)": "We = 1 / (10^(−dr/600) + 1)",
    "We:": "We:",
    "WIN LEVIATAN ESPORT": "VITÓRIA DA LEVIATAN ESPORT",
    "winner": "vencedor",
    "YouTube": "YouTube",
    "Z. Jack": "Z. Jack",
    "ZC ESPORTS · ZC26 · BSC (Brawl Stars Championship)": "ZC ESPORTS · ZC26 · BSC (Campeonato de Brawl Stars)",
    "ZC26 - Brawl Stars Championship": "ZC26 - Campeonato de Brawl Stars",
    "ZC26 1v1 Edición 4 · 3er y 4to Lugar": "ZC26 1v1 Edição 4 · 3º e 4º Lugar",
    "ZC26 1v1 Edición 4 · Gran Final": "ZC26 1v1 Edição 4 · Grande Final",
    "ZC26 1v1 Edición 4 · Ronda 1": "ZC26 1v1 Edição 4 · Rodada 1",
    "ZC26 1v1 Edición 4 · Ronda 2": "ZC26 1v1 Edição 4 · Rodada 2",
    "ZC26 1v1 Edición 4 · Semifinal": "ZC26 1v1 Edição 4 · Semifinal",
    "ZC26 1v1 · 3er y 4to Lugar": "ZC26 1v1 · 3º e 4º Lugar",
    "ZC26 1v1 · Gran Final": "ZC26 1v1 · Grande Final",
    "ZC26 1v1 · Ronda 1": "ZC26 1v1 · Rodada 1",
    "ZC26 1v1 · Ronda 2": "ZC26 1v1 · Rodada 2",
    "ZC26 1v1 · Semifinal": "ZC26 1v1 · Semifinal",
    "ZC26 es una organización independiente dedicada a la creación, desarrollo y gestión de torneos y eventos competitivos de Brawl Stars. Este evento no está afiliado, patrocinado ni respaldado por Supercell. Todos los nombres, marcas registradas, personajes e imágenes del juego pertenecen exclusivamente a sus respectivos creadores y propietarios.": "A ZC26 é uma organização independente dedicada à criação, desenvolvimento e gestão de torneios e eventos competitivos de Brawl Stars. Este evento não é afiliado, patrocinado ou endossado pela Supercell. Todos os nomes, marcas registradas, personagens e imagens do jogo pertencem exclusivamente aos seus respectivos criadores e proprietários.",
    "ZC26 ESPORTS™": "ZC26 ESPORTS™",
    "ZC26 GRAN FINAL": "ZC26 GRANDE FINAL",
    "ZC26 · 3er y 4to Lugar": "ZC26 · 3º e 4º Lugar",
    "ZC26 · Gran Final": "ZC26 · Grande Final",
    "ZC26 · Semifinal": "ZC26 · Semifinal",
    "zc26.esports.official@gmail.com": "zc26.esports.official@gmail.com",
    "Zona horaria:": "Fuso horário:",
    "Zyroxs escala 18 puestos tras coronarse campeón del Torneo Duelos ZC26": "Zyroxs sobe 18 posições após ser coroado campeão do Torneio Duelos ZC26",
    "© ZC26 | Todos los derechos reservados.": "© ZC26 | Todos os direitos reservados.",
    "·": "·",
    "¿Cómo se calcula la Clasificación?": "Como se calcula a Classificação?",
    "¿Quieres apoyar a ZC26? Con una donación desde 1 dólar a través de": "Você quer apoiar a ZC26? Com uma doação a partir de 1 dólar através do",
    "Álvaro": "Álvaro",
    "Última actualización: 30 agosto, 2026": "Última atualização: 30 de agosto de 2026",
    "Última actualización: 6 dic, 2025": "Última atualização: 6 de dez. de 2025",
    "Última actualización: viernes, 11 de Septiembre de 2026, 14:54": "Última atualização: sexta-feira, 11 de setembro de 2026, 14:54",
    "Última Clasificación": "Última Classificação",
    "Último partido importa": "A última partida importa",
    "ÚLTIMO PARTIDO IMPORTA": "A ÚLTIMA PARTIDA IMPORTA",
    "–": "-",
    "✕": "✕"
};
